### ISSUE TITLE
error when installing packages node

### ISSUE THREAD

**Issue by losorio35** [qdouble/angular-webpack2-starter#116]
first thank you for this great repository, https://github.com/qdouble/angular2webpack2-starter/tree/no-universal-support
when I install the packages with the npm i command, I get the following error:

npm ERR! Fetch failed https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz

that solution can give you is that please?

![image](https://cloud.githubusercontent.com/assets/7623449/19214636/2b962d0c-8d4e-11e6-814d-6fa00daa360f.png)

**Comment by DzmitryShylovich** [comment]
https://github.com/qdouble/angular-webpack2-starter/issues/114#issuecomment-252422545

**Comment by qdouble** [comment]
@losorio35 as linked in by @DzmitryShylovich this has been fixed already, make sure to clone or fetch the latest updates.
