### ISSUE TITLE
Question on SASS and testing

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular-webpack2-starter#119]
I've added support for SASS in my project (derived from this repo), but need help with test support of SASS. Currently, if I run 'npm run test' I get the following error:

>> ERROR in ./src/app/app.component.scss
Module parse failed: E:\Documents\Visual Studio 2015\Projects\NewsNotifier\src\app\app.component.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "~bootstrap-sass/assets/stylesheets/bootstrap";

Then it says __Module parse failed__ trying to parse *app.component.scss*. How do I set up this for testing? Please help.

**Comment by qdouble** [comment]
If you added sass support to the normal webpack config, you'd need to add it to the test config as well: https://github.com/qdouble/angular-webpack2-starter/blob/master/test-config/webpack.test.js

In most of the branches I'm using node-sass instead of the sass plugin because of AOT issues, but that will change when I switch to the AOT plugin

**Comment by alvipeo** [comment]
I added loader for SASS:
```
      {
        test: /\.(sass|scss)$/,
        loaders: ['css-to-string-loader', 'css-loader?sourceMap', 'resolve-url', 'sass-loader?sourceMap']
      },
```
but I get error which I don't understand at all :(
>> angular-webpack2-starter@1.4.5 test E:\Documents\Visual Studio 2015\Projects\angular2-bootstrap3
> karma start

>>11 10 2016 19:33:35.572:ERROR [karma]: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:536:5)
    at Object.onRender (E:\Documents\Visual Studio 2015\Projects\angular2-bootstrap3\node_modules\sass-loader\index.js:282:42)
    at E:\Documents\Visual Studio 2015\Projects\angular2-bootstrap3\node_modules\sass-loader\node_modules\async\dist\async.js:2231:35

what's this path.js? where is it?

**Comment by qdouble** [comment]
@alvipeo since your setup isn't really based on the way I have the starter setup, it's difficult to tell you where the problem is exactly. I suppose you could try using a loader like this instead:
`{ test: /\.scss$/, loaders: ['raw-loader', 'sass-loader'] },`

**Comment by alvipeo** [comment]
HUGE THANK YOU! that worked!
