### ISSUE TITLE
Feature Request: Reduce CPU usage of webpack dev server

### ISSUE THREAD

**Issue by DzmitryShylovich** [qdouble/angular-webpack2-starter#120]
For Mac: https://github.com/webpack/webpack/issues/701#issuecomment-216082726
For Windows: https://github.com/webpack/watchpack/pull/23

**Comment by qdouble** [comment]
@DzmitryShylovich I'll add  `ignored: /node_modules/` on watchOptions, but not sure what I'm supposed to be seeing on the first link?

**Comment by DzmitryShylovich** [comment]
> npm install fsevents in the project directory.

but `fsevents` is an OSX-only module so just ignore it. I missed that part.
