### ISSUE TITLE
Angular CLI support

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular-webpack2-starter#127]
Hey there :)
I'd like to use Angular CLI to generate Components, Services, etc. without having to create every file manually..

When I try to use for example:
```
ng g component test
```

I get
![image](https://cloud.githubusercontent.com/assets/3246782/19346468/c1deafc0-9143-11e6-816b-11ebd746adaa.png)

Is there any workaround to make this possible? Would be an awesome workflow boost!

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular-cli/issues/2670#issuecomment-253284904

**Comment by qdouble** [comment]
@DzmitryShylovich have you tried it out?

**Comment by qdouble** [comment]
played with it a bit, but not familiar enough with cli to know the best way to do this, but will accept a PR if you guys know the right way to make it work. Closing for now.
