### ISSUE TITLE
CSS files are outputted next to SCSS files

### ISSUE THREAD

**Issue by Waterstraal** [qdouble/angular-webpack2-starter#128]
Currently the build places built `CSS` files next to their `SCSS` counterparts in the `src` directory. However, the `CSS` files are **not** source-code (and should not be checked in or altered by devs). Developers could change the `CSS` and be surprised that their changes will be rolled back after a built. 

Is there a way to move the outputted `CSS` files elsewhere?

**Comment by DzmitryShylovich** [comment]
Just wait until https://github.com/qdouble/angular-webpack2-starter/issues/112 will be resolved.

**Comment by qdouble** [comment]
@Waterstraal right now I have the css set to be compressed, so hopefully that will enable you to tell the difference between the scss file and the generated css...but as @DzmitryShylovich pointed out... we'll no longer need to use this solution once we switch over to using the AOT webpack plugin, just waiting for some bugs to be fixed. Moving the file elsewhere would create other complications.
