### ISSUE TITLE
Branch with Bootstrap and Universal

### ISSUE THREAD

**Issue by karptonite** [qdouble/angular-webpack2-starter#129]
I see that universal was removed from the Bootstrap branch. Any particular reason? Seems like it would be as useful for Bootstrap as it is for Material Design.

**Comment by qdouble** [comment]
It wasn't compatible with Universal when I created it and I didn't know if there were any plans to make it compatible, but I think they say it's supposed to be compatible with it now. I suppose I can can add another branch that has them together when I have time.
