### ISSUE TITLE
Lazy route is not being lazy loaded

### ISSUE THREAD

**Issue by tsm91** [qdouble/angular-webpack2-starter#131]
Run the project, open up network tab in chrome devtools and navigate to http://192.168.56.1:3000/.

You can see `0.index.js` is being loaded. Inside the file i can see the `LazyModule`. Even tho you are on the dashboard page. Click the Lazy link to trigger navigation. You see no new requests in the network tab, hence it is already loaded.

**Comment by DzmitryShylovich** [comment]
https://vsavkin.com/angular-router-preloading-modules-ba3c75e424cb#.146587a1k
