### ISSUE TITLE
AOT - raw HTML template output next to aot compiled one

### ISSUE THREAD

**Issue by tdolny** [qdouble/angular-webpack2-starter#133]
Question.
Is the raw HTML template necessary in final production build output in AOT mode? 
I was surprised to see it next to ngfactory which I thought would be enough to generate views.

**Comment by DzmitryShylovich** [comment]
Are u sure this is the right place to ask such questions? :)

**Comment by tdolny** [comment]
Thought it could be a bug report or an enhancement suggestion. Sorry if it's not.

**Comment by qdouble** [comment]
@tdolny I don't fully understand your question, could you explain further?

**Comment by tdolny** [comment]
In /dist/client/index.js I get module definition for app.component.html with original HTML template like:
`"./src/app/app.component.html":function(e,t){e.exports='<md-sidenav-layout fullscreen>\n  <md-sidenav #sidenav [mode]="sideNavMode">\n    \n 
...
</my-store-devtools>\n'}`
with angular's interpolation and binding, which is later repeated in app.component.ngfactory.ts module  in the same file but in 'this.renderer.createElement()' functions manner.

**Comment by qdouble** [comment]
@tdolny ah ok. Well I agree with @DzmitryShylovich, that appears something you should file on the Angular github, as that seems to probably be an angular-compiler issue, not anything specific to this repo.

**Comment by tdolny** [comment]
Ok. Thank you for clarification.
