### ISSUE TITLE
Add variable to allow configuration options?

### ISSUE THREAD

**Issue by karptonite** [qdouble/angular-webpack2-starter#134]
Maybe I'm just not seeing it--is there a constant in `constants.js` that will allow me to set `config` params other than plugins or rules? for example, I'd like to include [`output.publicPath`](http://webpack.github.io/docs/configuration.html#output-publicpath), preferably on  per-environment level. This seems like something that might be able to simplify the constants file, if maybe there was one `CONFIG_FOO` var for each environment that included plugins, rules, etc, merged in with `webpackMerge`, but I don't understand the ins and outs of webpack enough to know if that would actually work.

**Comment by qdouble** [comment]
@karptonite you could modify the current code to be able to accommodate different output paths, but I really don't view it as a common enough need to put that in the seed. When you use the dev server, it doesn't even really output the files (they run in memory)...are you going to use a different path for AOT then JIT? or Universal? Not to say you won't, but it seems like something that won't be needed by most people.

Webpack merge isn't necessarily needed, you can simply use if statements to handle variables. I think this is more or less just a design preference... for me, it gets more complicated going back and forth between multiple configuration files, then just using an if statement to set the few differences between environments.

Right here: https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L255

You could simply add something like:
```bash
If (PROD) {
config.output = {
      path: root('dist/client'),
      filename: 'index.js'
    };
} else {
config.output = {
      path: root('dist/dev/client'),
      filename: 'index.js'
    };
}
```

**Comment by karptonite** [comment]
Thanks for considering! I wanted to ask before modifying the webpack.config.ts file directly.

FYI, here is my use case, and it probably is fairly uncommon: I'm adding an angular app as basically a subset of a much larger existing project. Our team uses a remote dev server, and the main html file is loaded from the remote, but for testing, we compile and serve the js from our local machines for now. My goal is to have webpack produce essentially an index.html file that has link(s) to the scripts prefixed by `localhost:port` that we can sync to our dev server. This may not be the best way to do this--I'm new to webpack--but it worked for us in the first iteration of our webpack setup.

For production, we will also want to generate a different path prefix for the scripts--we use a cdn to serve our js, separate from our main server. But we are pretty far from production yet--I figure I'll solve that problem when we come to it.
