### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by maku** [qdouble/angular-webpack2-starter#135]
I don't see an sourcemap support configured.  Is there anything I miss or is this not supported?

e.g. how can I debug the app in Chrome?

**Comment by DzmitryShylovich** [comment]
https://github.com/qdouble/angular-webpack2-starter/issues/126#issuecomment-253472604

**Comment by Waterstraal** [comment]
See #126

**Comment by maku** [comment]
Thank you!
