### ISSUE TITLE
Create separate bundles for external modules

### ISSUE THREAD

**Issue by bmurali31** [qdouble/angular-webpack2-starter#137]
Hi
Thank you for a awesome webpack starter repo. It works great and the configurations are very clean.

But, the current configuration creates a single bundle for all modules. Could you please help me in configuring webpack to create smaller bundles with one file for each external/internal module?

**Comment by qdouble** [comment]
Having a single bundle allows webpack to treeshake more effectively and to reduces the file size. If you want multiple bundles, you'll have to do that yourself by adding more entry files here: https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L235
