### ISSUE TITLE
ngrx store devtools not changing state

### ISSUE THREAD

**Issue by ryandegruyter** [qdouble/angular-webpack2-starter#140]
Not sure if it's an issue with ngrx store devtools or a configuration, but when you click the update store button, and you mark the 'Edit user action' in the devtools, the state of the app doesn't change.

**Comment by montella1507** [comment]
Devtools have lot of issues.. dotn use them atm:

https://github.com/ngrx/store-devtools/issues/25

**Comment by montella1507** [comment]
@ryandegruyter  it works again. You can use store/devtools again, just update to the newest version.

**Comment by qdouble** [comment]
@montella1507 is the time traveling working for you on the starter app? It doesn't appear to be for me, but not sure if I'm doing something wrong

**Comment by qdouble** [comment]
@ryandegruyter @montella1507 it should be fully fixed with this commit: https://github.com/qdouble/angular-webpack2-starter/commit/4aa1881974337d027c7fc9eb85afda5e92d63c08

**Comment by ryandegruyter** [comment]
Thanks @qdouble !
