### ISSUE TITLE
SCSS source map

### ISSUE THREAD

**Issue by montella1507** [qdouble/angular-webpack2-starter#141]
HI! 

At first i have to say, your works is f**** awesome!!! 

I think Angular-cli is x-years behind you :-(

Can i ask.. is it possible to use scss files with source maps and not as <style> tag?

**Comment by qdouble** [comment]
@montella1507 hey, I don't fully understand your question, but I'm probably not going to change the way scss is handled until we switch over to using a normal webpack scss plugin, but have to wait for the AOT plugin to get some more of the bugs out: https://github.com/qdouble/angular-webpack2-starter/issues/112

going to close for now, but if you can give me more detail, that would be cool

**Comment by montella1507** [comment]
@qdouble  HI Anthony,
at the moment, all compiled .scss files that i want to use are included in the webpage as Inline <style></style> TAG so it isn't possible to track down the original file and line, where is the concrete style defined. 

Your solution would be so perfect for us, unfortunately, our solution is pretty big and its essential for our frontend developers to be able to find the original place..

![image](https://cloud.githubusercontent.com/assets/10418323/19595574/c2ab02da-978a-11e6-9d48-8362c0e9a592.png)

So maybe the SASS loader is the way how to reach that behavior... Thx for your work. The solution how we could donate your time would be very appreciated.
