### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by sylc** [qdouble/angular-webpack2-starter#145]
Hi,

I have noted a difference in bundle sizes between an app bundled with the angular-webpack2-starter boostrap branch and one bundled with the angular-cli. (prod no AoT)
I took the app from the angular2-seed project ( https://github.com/mgechev/angular-seed) and just adjust the lazy loading of the 2 basic component. 

When built (prod no AoT) with this project - bootstrap branch, the main bundle is: 1,030 KB
When built (prod no AoT) with angular-cli the main same bundle is: 882 KB
(when built with angular2-seed, it is close to the cli size)

On another app i've done, the size jumps from 1.4MB to 1.7MB. I'm unsure why there is such a difference.  Compression plugin looks equivalent. I can't pin point the origin of the extra data.

I would like to use this project, however I would to understand the extra weight. Would you have any idea? thanks

**Comment by qdouble** [comment]
@sylc there shouldn't be a major difference, you have to make sure both have the exact same stuff loaded up (IE shim, polyfills, etc), same exact number of components, same 3rd party stuff etc... One thing I mostly notice is that when people compare other starters, they are not fully including vendor and polyfills size or the projects don't have the same contents... so unless it's an complete 1:1 comparison, then you can't expect the bundle size to be exactly the same.

**Comment by qdouble** [comment]
@sylc I'll close this for now as it's not actionable, but if you want me to re-open and look into it, you'd have to give me a link to the other seed project in which the app folder is the exact same. 

Make sure you are including everything needed to make the project run (some other projects split their bundles into 3 (app, polyfill, vendor) and might not include IE shim, while this project is just one bundle and includes IE shim). So if it's a full 1:1 match, then I can look. It would be impossible for me to tell otherwise.

**Comment by sylc** [comment]
@qdouble ok thanks for the reply. I can see that part of the difference depends on what polyfill is imported. As i'm a beginner, I just need to learn why each project require different ones. 
What is 'long-stack-trace-zone' used for? debugging?

this project:`
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'core-js/client/shim';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'ts-helpers';
`

angular-CLI project: `import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';`

**Comment by qdouble** [comment]
@sylc yes, long stack traces are for dev purposes. Those polyfills are not used on AOT build...for production, unless you have some 3rd party incompatibility, it's recommended to use AOT instead of JIT build

**Comment by qdouble** [comment]
@sylc Also, it's more useful to compare gzipped sizes rather than just minified sizes, as what may seem like significant difference when only minified may be very minor when gzipped.
