### ISSUE TITLE
Usage of angular-webpack2-starter for lib development

### ISSUE THREAD

**Issue by maku** [qdouble/angular-webpack2-starter#153]
Is angular-webpack2-starter a good option for lib development (e.g. when I have to develop base functionality for other developers). 

What has to adapted to be able to do this?

TIA

**Comment by qdouble** [comment]
I'm not fully sure as I've only been working on apps, not libs, but from reading comments from devs it seems that rollup/gulp setup is supposed to be best option for libs and small apps, while webpack seems to be the best option for mid to large size apps.

**Comment by DzmitryShylovich** [comment]
Yeah, rollup is recommended tool for libs. Take a look at https://github.com/ngrx/store
