### ISSUE TITLE
Use @ngtools/webpack instead of ngc for AOT

### ISSUE THREAD

**Issue by blacksonic** [qdouble/angular-webpack2-starter#155]
A Webpack plugin is available for AOT compilation.
Example project with it: https://github.com/blacksonic/angular2-aot-webpack

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/qdouble/angular-webpack2-starter/issues/112

**Comment by blacksonic** [comment]
Ok, closing it in favor of the original.
