### ISSUE TITLE
Polyfill request: integrate web-animations-js

### ISSUE THREAD

**Issue by tsm91** [qdouble/angular-webpack2-starter#160]
Since there is no `MY_POLYFILLS` array i opened an issue about this.

https://www.npmjs.com/package/web-animations-js should be added because the [animations api](https://angular.io/docs/ts/latest/guide/animations.html) is not cross browser compatible

**Comment by qdouble** [comment]
Hmm, not sure if I should add this as many apps might not use the animations api. I mean there are about 3 options for it right now, you could:
1) Use CDN: https://github.com/qdouble/angular-webpack2-starter/tree/master/src
2) Install and put in COPY_FOLDER array: https://github.com/qdouble/angular-webpack2-starter/blob/master/constants.js#L53
3) Install and put in the polyfill files like this one: https://github.com/qdouble/angular-webpack2-starter/blob/master/src/polyfills.browser.ts

**Comment by tsm91** [comment]
Alright, i went with the 3rd option.

I also add here? https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L236

**Comment by qdouble** [comment]
@tsm91 yeah, I'll probably add a constant for that though

**Comment by qdouble** [comment]
@tsm91 added a constant for it in this commit: https://github.com/qdouble/angular-webpack2-starter/commit/e5bb2b2c8932e7207bfc98c493e990933bec6312
