### ISSUE TITLE
index.html shows polyfill and vendor in a weird way

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular-webpack2-starter#161]
so when i view source of index.html it shows,

```html
<div id="str-dlls">
		<%= '<' %>script src="/polyfill.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
		<%= '<' %>script src="/vendor.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
	</div>
```

is this how its suppose to be ?

**Comment by qdouble** [comment]
That's there for when you are using dll on the dev server (for faster build and rebuilds), it's ignored in production builds
