### ISSUE TITLE
on input focus, mobile device

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular-webpack2-starter#162]
So on a mobile device when we click on the input field, keyboard opens but the page doesnt scroll so that the field is above the keyboard. I've tested this without doing any changes. Though such issue is not with `AngularClass/angular2-webpack-starter`.

**Comment by qdouble** [comment]
That's just based on these settings https://github.com/qdouble/angular-webpack2-starter/blob/master/src/index.html#L7

You can change it to whatever is desirable for you application.

**Comment by kodeine** [comment]
i've tried changing it but it doesnt work, any idea you can help with that?

**Comment by qdouble** [comment]
upload the repo with your changes and what you want me to test for exactly then I can try to fix it, but I'm not quite sure what issue you're having without that.

**Comment by kodeine** [comment]
@qdouble what is your email, ill send you repo etc there privately. or send me a quick email ahsen.m@gmail.com

**Comment by qdouble** [comment]
my username at gmail.com
