### ISSUE TITLE
Please help with AOT

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular-webpack2-starter#163]
Hey guys! Thank you @qdouble fir this great repo!

One question though - http://stackoverflow.com/questions/40450604/aot-function-calls-are-not-supported. 

Could anyone help please? I don't get it what it wants from me...

**Comment by qdouble** [comment]
Think it would be better for you to do a search of this issue on the Angular repo as this error is just a general AOT issue and not specific to this repo.
