### ISSUE TITLE
bootstrap branch, AOT compile - errors

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular-webpack2-starter#165]
Sorry, if this is a duplicate...

So I cloned bootstrap repo and when running 'yarn run compile' I get this:

>>ERROR in [default] E:\Documents\Visual Studio 2015\Projects\angular2-bootstrap\src\compiled\node_modules\@ng-bootstrap\ng-bootstrap\datepicker\datepicker.ngfactory.ts:140:8
Supplied parameters do not match any signature of call target.

>>ERROR in [default] E:\Documents\Visual Studio 2015\Projects\angular2-bootstrap\src\compiled\node_modules\@ng-bootstrap\ng-bootstrap\dropdown\dropdown.ngfactory.ts:92:19
Property '_open' is private and only accessible within class 'NgbDropdown'.

Obviously, has something to do with ng-bootstrap...

**Comment by d3viant0ne** [comment]
@alvipeo - Without doing any digging, you may want to try and lock the dependency for ng-bootstrap to the version in @qdouble's package.json and see if a AoT breaking change snuck into a patch or minor version release for ng-bootstrap.

**Comment by qdouble** [comment]
@alvipeo seems to work fine when updating to the latest: https://github.com/qdouble/angular-webpack2-starter/commit/e6823a33e6e0f77d45150405b9887e14804714cf
