### ISSUE TITLE
Noobish Question Deploy Universal:Aot

### ISSUE THREAD

**Issue by SerkanDayicik** [qdouble/angular-webpack2-starter#168]
How to deploy unviersal:aot build amazon s3 etc. like service ?
this need any node.js server ? and if u are using build universal aot give 2 folder client/ and server/ which use ?

**Comment by qdouble** [comment]
Your server would need to support node.js ...both the client and server folders are needed...the initial load would use the server folder, but then run off the client folder files when the app is fully loaded.
