### ISSUE TITLE
how to add an extra entry point?

### ISSUE THREAD

**Issue by tsm91** [qdouble/angular-webpack2-starter#170]
Hi @qdouble!

i would like to add an extra entry point for service-worker file. Webpack bundles both sw.ts and sw.dll.ts without error. But it generates extra code that references to dead code (other entry points vendor, polyfill) and get runtime error in development environment on http://localhost:3000/ after running npm start.

so http://localhost:3000/sw.js is the wrong one and http://localhost:3000/sw.dll.js is the good bundle

https://github.com/qdouble/angular-webpack2-starter/compare/master...tsm91:reproduce here is the reproduction of what i've tried

**Comment by tsm91** [comment]
ping @gdi2290

**Comment by qdouble** [comment]
@tsm91 currently, vendor/bundle files are all included in the main entry point...so if that's not needed for the service worker file, then you'd have to restructure that as well I suppose... however, I haven't dealt with service workers yet so I'm not fully sure what's supposed to be the best way to set it up.

**Comment by tsm91** [comment]
@qdouble i ended up creating a 2nd webpack config file and running the transpilation in a 2nd webpack process

what i can tell is the cause of this behaviour is DllReferencePlugin && DllPlugin
