### ISSUE TITLE
url-loader

### ISSUE THREAD

**Issue by cheater001** [qdouble/angular-webpack2-starter#172]
I have inserted into rules section of webpack.config:
`
{
        test: /\.(png|jpg|jpeg|gif|svg)$/,
        loader: 'url-loader?limit=5000&name=assets/img/[name].[hash].[ext]'
      }
`

And this html in component:
`<img src="./images/x.svg"/>`

When i run "yarn start" its working correctly (inserting inline image into html), but when i run "yarn run compile" webpack ignore such images and do nothing. What i do wrong?

**Comment by qdouble** [comment]
can you link to repo that shows this?

**Comment by cheater001** [comment]
Ofc
[repo](https://github.com/cheater001/angular-webpack2-starter.git)
http://localhost:3000/lazy

**Comment by qdouble** [comment]
@cheater001 this is probably due to the location of the ngc compiled files not being the same as a normal jit build and the plugin not compensating for that difference... did you test if it runs fine with cli or any other starter?
