### ISSUE TITLE
Question about referring constants.js 

### ISSUE THREAD

**Issue by maxisam** [qdouble/angular-webpack2-starter#175]
https://github.com/qdouble/angular-webpack2-starter/blob/master/src/app/reducers/index.ts

Why we don't need to import STORE_DEV_TOOLS here ?

**Comment by qdouble** [comment]
When project is generated by webpack, it's set as a global: https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L148
and then the type is declared here for typescript:
https://github.com/qdouble/angular-webpack2-starter/blob/master/src/custom-typings.d.ts#L30

**Comment by maxisam** [comment]
I see, thank you for explaining this. So what is the benefit of doing this instead of import it ?

**Comment by qdouble** [comment]
Constants are good for setting environment variables based on project
build.

**Comment by maxisam** [comment]
Thanks, I know Constants are good for setting environment variables. What I don't know is why using ` new DefinePlugin(CONSTANTS)` in webpack instead of importing it.

**Comment by qdouble** [comment]
With the DEV_TOOLS setting in particular, you could import that...but others that are set by the build, it would make more sense to do it in webpack.
