### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by FabioAntunes** [qdouble/angular-webpack2-starter#176]
First all, thank you for your hard work on this repo, looks amazing. I was exploring this repo for the first time and one thing that I noticed is that clicking on logout button, nothing happens and it returns an html response as payload. 

![screenshot from 2016-11-17 14 07 09](https://cloud.githubusercontent.com/assets/2544673/20392336/4a70ba08-accf-11e6-902c-481baf22cd83.png)

**Comment by qdouble** [comment]
@FabioAntunes Hey, yes, generally, you'd proxy it to your actual back office when you set it or change the link.. by default, it'll just pick up the html page since it can't find the link when you're using the dev server.
