### ISSUE TITLE
Builds fail with Node 7.1 on Windows

### ISSUE THREAD

**Issue by cgatian** [qdouble/angular-webpack2-starter#177]
Looks like `node-sass` needs to be bumped to version 3.13.0.

**Comment by qdouble** [comment]
@cgatian I bumped it in this commit, does it solve the issue? https://github.com/qdouble/angular-webpack2-starter/commit/c66ff61f37c453bb1e82f3266afd5a67ff5f069b

**Comment by cgatian** [comment]
Fixes the node-sass issue. Now another unrelated issue is occurring; will have to wait for Node.js 7.2 to verify. 

https://github.com/nodejs/node/issues/9542

**Comment by egil** [comment]
@qdouble / @cgatian, is there a work around while we wait for the next version of node?

**Comment by gausie** [comment]
@egil downgrade to LTS

**Comment by qdouble** [comment]
yeah, just downgrade 6.6.0 has no issues

**Comment by egil** [comment]
Ahh ok, though 7.x was required since it was installed with yarn.

**Comment by cgatian** [comment]
@egil Sorry I dont know what you mean. I installed 7.1 and ran into the issue, and uninstalled/installed back to 6.9 and no longer had any issues.

**Comment by egil** [comment]
@cgatian, when I installed `yarn` via choco, it first installed models 7.1, that's why I thought it was required.

**Comment by egil** [comment]
@cgatian, just installed 7.2 and it seems to solve the issue on my computer.

**Comment by cgatian** [comment]
Verified working on 7.2 with latest node-sass
