### ISSUE TITLE
How to import a module?

### ISSUE THREAD

**Issue by wizardnet972** [qdouble/angular-webpack2-starter#178]
Hi, I want to import mongoose.

So I did: `npm i mongoose --save`

But in server.ts, vscode show error `cannot find module` in this line:
`import * as mongoose from 'mongoose';`

What I missing here?

**Comment by DzmitryShylovich** [comment]
https://github.com/Automattic/mongoose#connecting-to-mongodb
> var mongoose = require('mongoose');

**Comment by wizardnet972** [comment]
@DzmitryShylovich The problem is vs code **intellisense** said cannot find module in this line.
do I need to configure something here?

**Comment by wizardnet972** [comment]
@DzmitryShylovich 
Find it! just to add  "@types/mongoose": "4.5.42" in package.json :)
