### ISSUE TITLE
How to integrate socket into dev server?

### ISSUE THREAD

**Issue by wizardnet972** [qdouble/angular-webpack2-starter#179]
Hi,

I want to use sockets in this project. I find that I should use sockjs vs socket io.

my console logs in server.ts not showing on node-console/browser. I see that server.ts is for AoT only. :(

So where and how to configure sockjs/socket.io?

**Comment by qdouble** [comment]
The server.ts file is for universal, if you're not using universal, then just use this branch: https://github.com/qdouble/angular-webpack2-starter/tree/no-universal-support

You can't put sockjs/socket.io on the webpack dev server, but you could potentially add it to the prodsever here: https://github.com/qdouble/angular-webpack2-starter/blob/master/prodserver.js .

**Comment by wizardnet972** [comment]
@qdouble What about mongoose? 
Where I can config this `mongoose.connect('mongodb://127.0.0.1:27017/chat');`?
Same answer or any other way?

**Comment by qdouble** [comment]
Yeah, you'd have to run it on the prodserver.js file
