### ISSUE TITLE
Please help with running tests - Failed to load ~bootstrap-datepicker

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular-webpack2-starter#180]
I'm using Minimal branch and I use bootstrap-datepicker and SASS in my project. All works in run-time, but when I run 'npm run test' I get the error:

>> Failed: Uncaught (in promise): Failed to load ~bootstrap-datepicker/... 

Here's how is this used:
```
@Component({
    selector: 'ilg-datepicker',
    template: `...`,
    providers: [...],
    encapsulation: ViewEncapsulation.None,
    styleUrls: ["./datepicker.component.scss"]
})
export class IlgDatepicker implements OnInit, AfterViewInit, ControlValueAccessor {
...
}
```
and the datepicker.component.scss:
```
@import "~bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css";
```
Can anybody help with this? I don't know what does it want from me...

**Comment by qdouble** [comment]
@alvipeo 

Tests have separate webpack config, so if you added anything to the main config, make sure you add it to the test webpack config: https://github.com/qdouble/angular-webpack2-starter/blob/master/test-config/webpack.test.js

**Comment by alvipeo** [comment]
Of course I did. But it seems like it's not enough. It's something else.

**Comment by qdouble** [comment]
well since I didn't implement sass in the minimal branch, it may be related to your implementation of that... did you try to see if it fails with the full relative path?

**Comment by alvipeo** [comment]
I added this to loaders to test config:
```
      {
        test: /\.scss$/,
        loaders: ['raw-loader', 'sass-loader']
      },
```
don't know what else should be there.

As a side note - Bootstrap branch is great to have, but I use Minimal for a "raw" Bootstrap just because I want to keep my runtime dependencies as min as possible. Also, it helps to learn thing (even though this knowledge is a garbage, really... but it's the state of dev right now... sigh)

**Comment by qdouble** [comment]
try to see whether or not it's just not finding it by putting the relative path to the node_modules folder ('../../node_modules/bootstrap-datepicker/...`)

**Comment by alvipeo** [comment]
That was it! Abs path helped:
```
@import "/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css";
```

**Comment by alvipeo** [comment]
thanks!
