### ISSUE TITLE
Can't resolve './compiled/src/app/app.module.universal.browser.ngfactory'

### ISSUE THREAD

**Issue by Tuizi** [qdouble/angular-webpack2-starter#183]
Hello,

I try to use the starter with a CI, and here are the commands executed by it:

```
yarn
yarn run build:universal:aot:prod
```

But this doesn't work, I get the error:

```
ERROR in ./src/main.browser.universal.aot.ts
    Module not found: Error: Can't resolve './compiled/src/app/app.module.universal.browser.ngfactory' in '/Users/fr/Projects/imp/web/src'
     @ ./src/main.browser.universal.aot.ts 6:47-115

    ERROR in [default] /Users/fr/Projects/imp/web/src/main.browser.universal.aot.ts:6:35
    Cannot find module './compiled/src/app/app.module.universal.browser.ngfactory'.
```

I have the same thing on my computer by just cloning the repository (universal+bootstrap) and running those 2 commands.

To **solve** that I have to run `yarn run universal:aot` before.

**Comment by qdouble** [comment]
@Tuizi It isn't a bug, you'd only run the scripts directly commands with AOT if you wanted to rebuild something that was already compiled... otherwise, you'd have to run a compile command first.

**Comment by Tuizi** [comment]
So what is the correct commands to run for a CI, I have just run:

```
yarn
yarn run test:once
```

Is it enough to consider that everything is fine and will work for AOT & Universal?

**Comment by qdouble** [comment]
@Tuizi there are some issues with Universal in AOT mode: https://github.com/qdouble/angular-webpack2-starter/issues/118 ... I think there are some hacks to make it work now, but I'll focus on that next week when I have time to play with it.

The only way to fully make sure your code works in different environments is e2e tests. Unit tests basically test a JIT, client side build.

**Comment by Tuizi** [comment]
Ok thank you very much. You really did a great job with this starter! Thank you for that too 💯

**Comment by kadosh1000** [comment]
@qdouble any news regarding this issue? I am running into the same problem, only using AOT without Universal

**Comment by qdouble** [comment]
@kadosh1000 will update the universal repos sometime this week or next week, its' been merged into angular core

**Comment by kadosh1000** [comment]
@qdouble as mentioned I am not using Universal at all. I am calling `build:aot:dev` which causes the same error.
After calling `compile:aot` and reruning `build:aot:dev` I stopped getting the error.
BTW I have already removes universal and added @angular/platform-server to use it instead.

**Comment by qdouble** [comment]
@kadosh1000 if your using the Universal branch, I haven't updated it in a while so it may have issues...but the no-universal-support branches work just fine, so you could use that in the meantime until I update the universal branches. Universal lagged far behind the rest of angular for a while so it was difficult to do updates on it.
