### ISSUE TITLE
Styles not reloading in HMR

### ISSUE THREAD

**Issue by Kamshak** [qdouble/angular-webpack2-starter#184]
When using HMR and editing styles i need to refresh the entire page. Is there a way to fix this?

using yarn run start:hmr and editing main.scss for testing

**Comment by qdouble** [comment]
@Kamshak if you need to refresh the entire page, then you shouldn't be using HMR mode as the principle of it is just reloading the edited module.

**Comment by Kamshak** [comment]
Don't need it very often but sometimes i create some global styles (buttons etc) and would love to see the styles applied while keeping current state intact. Any way to refresh styles at a global level additionally to the component level?

**Comment by qdouble** [comment]
@Kamshak yeah, I understand what you're trying to do but I don't believe there is a way without creating some sort of customized plugin. I typically just end the node process and switch between hmr mode and normal dev server mode when I need to make changes that require full page refresh.

**Comment by Kamshak** [comment]
OK, too bad! Works great in component mode which makes for an amazing workflow. Thanks for the great starter :+1:

**Comment by inzerceubytovani** [comment]
I just found out, @Kamshak if you use styleUrls with path to css file in components, hmr works perfectly. Hope still helps

**Comment by Kamshak** [comment]
yep, works great for components, just doesn't work for the main.scss and includes of that file. It's possible to work around is by using no StyleEncapsulation and putting the global styles in the app component
