### ISSUE TITLE
Upgraded some to latest - question

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular-webpack2-starter#185]
I created a project based on this great repo (but **Minimal** one) - https://github.com/alvipeo/angular2-plain-bootstrap. But when I run build I get these kind of errors:

>>ERROR in ./~/css-loader?sourceMap!./~/resolve-url/resolve-url.js!./~/sass-loader?sourceMap!./src/app/shared/datepicker/datepicker.component.scss
Module build failed: ReferenceError: document is not defined

and

>>ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"bootstrapRelPath":"../bootstrap-sass"}!./~/source-map-loader!./~/source-map-loader!./~/bootstrap-loader/no-op.js

I have no idea why I get them. Please help me out here.

Am I the only one who wants to have "clean" Bootstrap in their project? Just to learn and lower the number of dependencies.

**Comment by qdouble** [comment]
Well not fully sure since it's beyond what's in the project by default, but using a sass loader directly would be problematic anyway in AOT mode

**Comment by alvipeo** [comment]
Well, I guess I need to return to the pain old css then... Which is a pity.

**Comment by qdouble** [comment]
In the other branches, I use node-sass and then import the css file.... but it would be safe to use scss directly when we switch to using the AOT plugin, but we're still waiting for some bugs to be fixed.
