### ISSUE TITLE
Integrate angular/flex-layout

### ISSUE THREAD

**Issue by alexthewilde** [qdouble/angular-webpack2-starter#186]
[Flex layout](https://github.com/angular/flex-layout) has been released as the official Layout engine for ng applications. It would be great having it as part of angular-webpack2-starter.

**Comment by DzmitryShylovich** [comment]
it's not published to npm yet

**Comment by alexthewilde** [comment]
@DzmitryShylovich true, I've been struggling to get it installed manually.

**Comment by qdouble** [comment]
looks coool, would have to play with it a bit before potentially integrating. It comes out today?

**Comment by losorio35** [comment]
Qdouble, first congratulate you on this great seed.
I would like to know if you plan to integrate this https://github.com/angular/flex-layout#fast-start layout into the repository?

**Comment by d3viant0ne** [comment]
Flex layout is in no way ready to be used as a core library in a starter project.

**Comment by Tuizi** [comment]
Flex Layout is ready and already wildy used, http://caniuse.com/#feat=flexbox but it should be a choice made after using a starter project... not imposed by it. Another popular layout coming is the Grid Layout http://caniuse.com/#feat=css-grid and in the future, developers will use the layout they want for their app

**Comment by d3viant0ne** [comment]
@Tuizi - Not flexbox which is what you are referencing. Flex Layout is an angular flexbox library in very early alpha and as I stated above, is in no way ready.

**Comment by qdouble** [comment]
I've been building and using this from master...but I don't think they are even putting it out on npm yet. I'll close this, as I don't think it's necessary to include it.

**Comment by alexthewilde** [comment]
I would reconsider this as soon as flex layout has got a public release. After all you're shipping this starter with Material 2 which itself refers to the upcoming release of flex layout as the official layout engine. 

Long story short, right now you can't build an app using this starter without having to integrate an extra layout lib manually.

**Comment by d3viant0ne** [comment]
@alexthewilde - That is kind of the point, it's a starter. Adding flex-layout limits this `starters` usefulness to a development community with a wide range of `requirements` for which flex-layout may or may not fit the bill.

On persons convenience item is another person pain in the ass.

**Comment by qdouble** [comment]
I mean it depends on how much it plays into material when it's fully released. If it becomes a default option for layout, then of course, it will make sense to include it...but if it doesn't seem vital, then I won't include it. Obviously, this is not a minimal starter kit (outside of the minimal branch), but we don't necessarily want to include the kitchen sink either... we'll see how it develops.

**Comment by fdambrosio** [comment]
I can't use flex-layout v2.0.0-beta.0 using npm with this starter kit because I think that it needs Angular 2.2.3. 
I have a lot of UNMET PEER DEPENDENCY 

```
UNMET PEER DEPENDENCY @angular/common@2.1.0
├── UNMET PEER DEPENDENCY @angular/compiler@2.1.0
├── UNMET PEER DEPENDENCY @angular/core@2.1.0
├── @angular/flex-layout@2.0.0-beta.1 
├── UNMET PEER DEPENDENCY @angular/http@2.1.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.1.0
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.1.0
├─┬ angular2-universal-polyfills@2.1.0-rc.1
│ └── es6-promise@3.0.2 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
├── UNMET PEER DEPENDENCY tslint@4.1.1
└── UNMET PEER DEPENDENCY webpack@2.2.0-rc.2

npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/http@^2.2.0 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/common@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/compiler@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/core@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/platform-browser@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/platform-browser-dynamic@^2.1.2 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm WARN html-webpack-plugin@2.24.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN ngrx-store-freeze@0.1.5 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN ngrx-store-freeze@0.1.5 requires a peer of @angular/core@^2.3.0 but none was installed.
npm WARN string-replace-loader@1.0.5 requires a peer of webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.1 requires a peer of @angular/common@~2.2.3 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.1 requires a peer of @angular/core@~2.2.3 but none was installed.

```

**Comment by fdambrosio** [comment]
I've fixed dependency error, but on console I have an error: "ctorParameters.map is not a function" if I use flex-layout v2.0.0-beta.0 
Downgrading to alpha version, flex layout works

**Comment by alexthewilde** [comment]
flex-layout is officially available via npm now. It requires angular 2.4.x though, while angular-webpack2-starter is still at 2.1.2 for [incompatibility reasons with univeral](https://github.com/qdouble/angular-webpack2-starter/issues/191).

**Comment by losorio35** [comment]
Hello everyone, is already included, in this repo Flex layout?

**Comment by qdouble** [comment]
@losorio35 haven't put it, but it should be easy to add on the non-universal branches

**Comment by alexthewilde** [comment]
@losorio35 what @qdouble said. It's not compatible with the universal branch, it does work however with the other ones because flex-layout requires up to date dependencies. This eventually made me switch away from the universal branch.

**Comment by qdouble** [comment]
yeah, universal isn't ready for primetime until it's put into angular core in angular 4
