### ISSUE TITLE
Using "If" statements in template

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular-webpack2-starter#187]
Hey there,
How can I use "if" statements like this?

When I do this
```
	<%= if (ENV === 'development') { =%>
      <script>
        trackingCode = 'xxxxx';
      </script>
	<%= } =%>  
```

I get this error
```
Module build failed: SyntaxError: Unexpected token if
```

Thank you in advance :)

**Comment by qdouble** [comment]
I think some of the syntax and setup of that has changed in the newer releases of webpack...also with how the project is currently setup, that would only be readable when using the dev server as in production builds the index.html file is copied over and not generated with the HtmlWebpackPlugin
