### ISSUE TITLE
remove ng-bootstrap

### ISSUE THREAD

**Issue by Tuizi** [qdouble/angular-webpack2-starter#189]
Hello,

I'm trying to have only ng2 with ngStore, AOT and Universal so I started from the bootstrap + universal branch.

I have removed all references to ng-bootstrap but when I remove the line:
`{ test: /ng-bootstrap/, loader: 'imports-loader?window=>global' },` from webpack.config.ts.

I get the error:
```bash
[./src/app/app.module.universal.node.ts] ./src/app/app.module.universal.node.ts 363 bytes {0} [built] [failed] [1 error]
[./src/polyfills.server.ts] ./src/polyfills.server.ts 81 bytes {0} [built]
[./src/rxjs.imports.ts] ./src/rxjs.imports.ts 891 bytes {0} [built]
[./src/server.routes.ts] ./src/server.routes.ts 358 bytes {0} [built] [failed] [1 error]
```
when running `yarn run universal:aot`.

Do you know why?
Can we have a branch without bootstrap? (I can do it if I understand why removing this line from webpack.config break the build)

**Comment by DzmitryShylovich** [comment]
https://github.com/qdouble/angular-webpack2-starter/tree/universal-aot-wip

**Comment by Tuizi** [comment]
Ok I put 
`{ test: /@angular/, loader: 'imports-loader?window=>global' },`
instead of 
`{ test: /ng-bootstrap/, loader: 'imports-loader?window=>global' }`

**Comment by qdouble** [comment]
will close this for now, already a thread of AOT, will update the setup of that soon, just trying to finish up a project right now.
