### ISSUE TITLE
[Question] Webpack DLL's & "app_assets"

### ISSUE THREAD

**Issue by jgodi** [qdouble/angular-webpack2-starter#190]
I noticed that in the DLL config there is a reference to "app_assets", but then this is not referenced anywhere else. Is this required? What does it do?

https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L221

Thanks!

**Comment by qdouble** [comment]
It's just pointing the dll configuration to the main application file... it's how it was set up in other reference projects... if it's not needed, then let me know.
