### ISSUE TITLE
update angular to 2.2.3?

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular-webpack2-starter#191]
as the title says, can we move to latest version of angular, since it supports meta service which will be very useful in universal.

**Comment by qdouble** [comment]
@kodeine I see the official universal starter repo is only on 2.1.2 and has issues when you try to upgrade it. Soon the core angular team is supposed to be universal into the core testing setup, so hopefully that will help things. As it is currently, just about every other upgrade of Angular breaks with Universal.

**Comment by DzmitryShylovich** [comment]
> it supports meta service

cool but meta is not yet a part of angular :)

**Comment by cgatian** [comment]
Whats "meta service"?

**Comment by kodeine** [comment]
@qdouble 
i was actually talking about the following dependencies to be updated.

```
 "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/compiler-cli": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/platform-server": "2.1.0",
```

**Comment by qdouble** [comment]
@kodeine the universal starter repo is only updated to 2.1.2... Universal breaks with the newer angular updates as the angular team doesn't currently include it in their tests, that's why I've been updating the universal branch slower than the other branches

**Comment by fdambrosio** [comment]
there's news?

**Comment by qdouble** [comment]
@fdambrosio no, seems the universal branches will lag behind until they finish bringing it into and testing it against the angular core repo

**Comment by fdambrosio** [comment]
with npm install I have this warnings: 

```
npm WARN @angular/flex-layout@1.0.0-alpha.12 requires a peer of @angular/common@~2.2.3 but none was installed.
npm WARN @angular/flex-layout@1.0.0-alpha.12 requires a peer of @angular/core@~2.2.3 but none was installed.
npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-alpha.11-3 requires a peer of @angular/http@^2.2.0 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/common@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/compiler@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/core@^2.1.2 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/platform-browser@^2.1.2 but none was installed
.
npm WARN angular2-google-maps@0.16.0 requires a peer of @angular/platform-browser-dynamic@^2.1.2 but none was i
nstalled.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm WARN html-webpack-plugin@2.24.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN ngrx-store-freeze@0.1.5 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN ngrx-store-freeze@0.1.5 requires a peer of @angular/core@^2.3.0 but none was installed.
npm WARN string-replace-loader@1.0.5 requires a peer of webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta but none w
as installed.
```

**Comment by JefferE** [comment]
I get warnings with yarn as well with absolutely fresh checkout of this project.

Seems all seed projects have issues like this where they're never fully up-to-date.

```
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Incorrect peer dependency "rxjs@5.0.0-rc.4".
warning Incorrect peer dependency "@angular/core@^2.3.0".
warning Incorrect peer dependency "webpack@1 || ^2.1.0-beta".
warning Unmet peer dependency "jasmine-core@*".
warning Incorrect peer dependency "webpack@1 || 2 ||
```

**Comment by fdambrosio** [comment]
How can we fix?

**Comment by fdambrosio** [comment]
there's a simple way to migrate our material+universal project to bootstrap+universal kit?  
We need angular2+webpack+universal+responsive/adaptive layout, please can you tell how can do that?

**Comment by qdouble** [comment]
@fdambrosio the branches are similar, so you could just manually make the changes, or follow instructions here: https://github.com/qdouble/angular-webpack2-starter/wiki/Recommended-Steps-for-Merging-Starter-into-Existing-Project

**Comment by fdambrosio** [comment]
thanks @qdouble 
bootstrap + universal works good?

**Comment by qdouble** [comment]
@fdambrosio in JIT mode, there were no issues the last time I checked

**Comment by fdambrosio** [comment]
I'm testing a fresh bootstrap+universal starter kit. 
with `yarn run universal` the homepage crash with this error: 

```
ReferenceError: window is not defined
    at _requestIdle (/node_modules/@angularclass/idle-preload/dist/index.js:17:15)
    at eInjector.get (e.ngfactory.js:139:99)
    at eInjector.get (e.ngfactory.js:144:115)
    at eInjector.get (e.ngfactory.js:149:85)
    at eInjector.createInternal (e.ngfactory.js:464:131)
    at eInjector.NgModuleInjector.create (/node_modules/@angular/core/bundles/core.umd.js:6968:80)
    at NgModuleFactory.create (/node_modules/@angular/core/bundles/core.umd.js:6953:22)
    at /node_modules/@angular/core/bundles/core.umd.js:6671:47
    at ZoneDelegate.invoke (/node_modules/zone.js/dist/zone-node.js:232:26)
    at Object.onInvoke (/node_modules/@angular/core/bundles/core.umd.js:6229:41)
```

**Comment by qdouble** [comment]
@fdambrosio ah, just added that recently, try to do a git checkout to an earlier commit, I'll probably have to roll back some of the updates

**Comment by Tuizi** [comment]
Yeah idle-preload will never work with Universal.  I should have used a
switch is the code to activate it only when it is executed by the browser.

**Comment by Tuizi** [comment]
You can rollback it until I do the fix

**Comment by fdambrosio** [comment]
thanks, I'm trying 75b1b832157491569b0a1c04c9f1cc0c3d47b05e and it builds and run locally, but it doesn't load style.css  main.css and index.js (404 not found) 
on server I have this error: 

```
# node index.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'core-js/es6/reflect'
```

**Comment by Phoscur** [comment]
please update for angular 4.0.0

**Comment by qdouble** [comment]
closing... universal branches will be updated when it's stable in Angular 4
