### ISSUE TITLE
intl polyfill not available

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular-webpack2-starter#193]
in the index.html we have:
	<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=console.*,Intl.~locale.en&gated=1"></script>

but if I go to the link, I get an empty file!

**Comment by karolmie1** [comment]
Hey, this is not a problem. It only means that your browser don't require any pollyfils. 

If you were to load the site with outdated browser without some cool features some polyfills would pop up.
