### ISSUE TITLE
Facing Problem During 'yarn start'

### ISSUE THREAD

**Issue by nirajrajgor** [qdouble/angular-webpack2-starter#194]
I am getting these error on yarn start. Please tell where i am doing wrong. I am using windows 10 operating system.

g:\Livefiesta\Websites\livefiesta-angular\livefiesta>yarn start
yarn start v0.17.10
$ npm run server:dev

> livefiesta@1.14.0 server:dev g:\Livefiesta\Websites\livefiesta-angular\livefiesta
> npm-run-all -p -r webdev sass:watch

'npm-run-all' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! livefiesta@1.14.0 server:dev: `npm-run-all -p -r webdev sass:watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the livefiesta@1.14.0 server:dev script 'npm-run-all -p -r webdev sass:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the livefiesta package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -p -r webdev sass:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs livefiesta
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls livefiesta
npm ERR! There is likely additional logging output above.

**Here is My Log file**
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error livefiesta@1.14.0 server:dev: `npm-run-all -p -r webdev sass:watch`
22 error Exit status 1
23 error Failed at the livefiesta@1.14.0 server:dev script 'npm-run-all -p -r webdev sass:watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the livefiesta package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all -p -r webdev sass:watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs livefiesta
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls livefiesta
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DzmitryShylovich** [comment]
`npm i` or `yarn`

**Comment by nirajrajgor** [comment]
@DzmitryShylovich Already performed command 'yarn'. It was successfull with some warnings.
The warning were as follows:


g:\Livefiesta\Websites\livefiesta-angular\livefiesta>yarn
yarn install v0.17.10
info No lockfile found.
[1/4] Resolving packages...
warning protractor > jasmine > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning watch-run > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning watch-run > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning phantomjs-prebuilt > request > node-uuid@1.4.7: use uuid module instead
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Incorrect peer dependency "@angular/compiler@~2.2.0".
warning Incorrect peer dependency "@angular/core@~2.2.0".
warning Unmet peer dependency "jasmine-core@*".
error An unexpected error occurred: "ENOENT: no such file or directory, open 'g:\\Livefiesta\\Websites\\livefiesta-angular\\livefiesta\\node_modules\\@types\\body-parser\\package.json'".
info If you think this is a bug, please open a bug report with the information provided in "g:\\Livefiesta\\Websites\\livefiesta-angular\\livefiesta\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**After this i performed 'yarn start' and got errors.**
Can you point out what i am doing wrong, since i am new to yarn.

**Comment by DzmitryShylovich** [comment]
nuke node modules and `npm i`

**Comment by nirajrajgor** [comment]
**command 'nuke node modules' gives following error.**
G:\Livefiesta\Websites\livefiesta-angular\livefiesta>nuke node modules
'nuke' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alvipeo** [comment]
:)

**Comment by alvipeo** [comment]
he meant to delete node_modules folder

**Comment by nirajrajgor** [comment]
@alvipeo @DzmitryShylovich Thanks you so much. It worked. I think i should close this issue now.
