### ISSUE TITLE
Using AOT compilation and DLLs together.

### ISSUE THREAD

**Issue by velo333** [qdouble/angular-webpack2-starter#198]
Is it possible to use AOT compilation and DLL generation together in dev mode? How to do that?

**Comment by qdouble** [comment]
It's possible that  it's something I can look into if it's possible when we start using the webpack AOT plugin, but I doubt you could right now and the project isn't currently setup around using AOT in development. When they enable watch mode for AOT, it may be a solution worth looking into, as without it, using AOT in dev is painfully slow.

**Comment by velo333** [comment]
Thank you. It resolved my doubts.
