### ISSUE TITLE
Problem with repository

### ISSUE THREAD

**Issue by losorio35** [qdouble/angular-webpack2-starter#199]
hello, I just updated my application to a new version of this architecture
Https://github.com/qdouble/angular-webpack2-starter/tree/no-universal-support

And now every time my effects consult or record my service, send 2 times repeated the same date.

For example if I make a recording, by means of my effect it does 2 times.

Has anyone had the same problem with this repository?

Since with my previous version of this same architecture I do not have this problem

![two-petition](https://cloud.githubusercontent.com/assets/7623449/20985159/3f0498c0-bc91-11e6-9e8e-3b6a9971c4cd.png)

**Comment by qdouble** [comment]
@losorio35 is it happening on a lazy loaded module? If so, it's related to this router bug: https://github.com/angular/angular/issues/12869. You can roll back to 2.1.2/3.1.2 until they fix it.

**Comment by losorio35** [comment]
qdouble, Thanks you're right that was the problem
