### ISSUE TITLE
Using webpack obfuscator with starter

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular-webpack2-starter#200]
I am using [webpack-obfuscator](https://github.com/javascript-obfuscator/webpack-obfuscator) to obfuscate the JS. It works fine but its encrypting all the vendor files too. Is there a way i can seperate the vendor, this way i can obfuscate project src only.

Your help is appreciated.

Thanks

**Comment by qdouble** [comment]
@kodeine you'd have to separate the entry of your vendor files...this project is currently built around having it all in one...but it shouldn't be too difficult for you to separate them. Doing so will increase build size a bit, though.

**Comment by kodeine** [comment]
@qdouble i'm not much familiar with webpack and having hard time splitting js using CommonsChunkPlugin. Can you please make an example?

**Comment by qdouble** [comment]
@kodeine on the 4 entry conditions right there (https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L246), there's a part that says main, which is the main entry file of the application. If you wanted to separate the vendor files, you'd have to create a vendor entry file and add it above 'main'
