### ISSUE TITLE
aot app not running on no-universal-branch

### ISSUE THREAD

**Issue by karolmie1** [qdouble/angular-webpack2-starter#201]
Steps to reproduce: 
1. Checkout fresh repository
2. yarn
3. yarn run compile
4. yarn run prodserver 

Effect:
Page is "Loading..."

Console output: 
No provider for t!  (unknown)

**Comment by DzmitryShylovich** [comment]
try to use `npm` instead of `yarn`. still the same error?

**Comment by karolmie1** [comment]
@DzmitryShylovich 
Sorry to say that, but yes. Even after cleaning node_modules.
Minimal branch works ok for me.

**Comment by qdouble** [comment]
@karolmie1 I just reverted the last commit I made on that branch here, so it should work: https://github.com/qdouble/angular-webpack2-starter/commit/06302608cdbcf97cf1bc17f24d5e24eb41175a29
