### ISSUE TITLE
Cannot find module problem with 3rd party lib

### ISSUE THREAD

**Issue by rmarchiori** [qdouble/angular-webpack2-starter#202]
Hello guys,

I'm having trouble when trying to add 3rd party modules to the project.

I've downloaded the project and added the following code. 

Add module to package.json

**package.json**

`    "qs":"6.3.0",`

Added the import and the following test code to component constructor. 

**app.component.ts**

`import * as qs from "qs";`

Code added to constructor

`console.log('qs', qs);

    var obj = qs.parse('a=c');
    console.log('obj', obj);

    var str = qs.stringify(obj);
    console.log('str', str);`

I run npm install then npm start and here is the outcome:

![image](https://cloud.githubusercontent.com/assets/13880165/21012380/ac97d00e-bd23-11e6-81f3-c4c6ab3b8af9.png)

But even with that webpack error the site still works:

![image](https://cloud.githubusercontent.com/assets/13880165/21012404/deee39bc-bd23-11e6-8a30-849146e8c375.png)

What am I doing wrong?  Any thoughts?

Thanks,

**Comment by karolmie1** [comment]
Hey! Maybe try to require this library instead of importing it.
If you want to import it, then take a look at: 
https://github.com/Microsoft/TypeScript/issues/3019

(I am not contributor, but I'm currently testing this repository, so maybe their answer will be better)

**Comment by qdouble** [comment]
@rmarchiori add it to the vendor dll's list. For fast dev server loading, it loads up dependencies in dlls. 
https://github.com/qdouble/angular-webpack2-starter/blob/master/constants.js#L65 
https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L97
