### ISSUE TITLE
Update to Typescript 2.1.4

### ISSUE THREAD

**Issue by cgatian** [qdouble/angular-webpack2-starter#203]
* Update package.json Typescript to `~2.1.4`
* Update awesome-typescript-loader to `3.0.0-beta.9`
* Remove all instances of `ForkCheckerPlugin` from:
    * tsconfig.json
    * webpack.test.js
    * webpack.config.js
* Clear `.awcache` directory  (at least I needed to this may not be required)

**Comment by cgatian** [comment]
I should also comment, there's probably additional configuration needed.  This got me working at least.

**Comment by qdouble** [comment]
@cgatian I don't think angular officially supports typescript 2.1 though

**Comment by cgatian** [comment]
There's issues with code coverage.

https://github.com/s-panferov/awesome-typescript-loader/issues/293
https://github.com/s-panferov/awesome-typescript-loader/issues/290

**Comment by d3viant0ne** [comment]
The angular team has stated they don't support 2.1.x and users shouldn't switch until Angular 4.x

**Comment by qdouble** [comment]
Yeah, will wait until Angular team supports it.
