### ISSUE TITLE
Update to istanbul-instrumenter-loader 1.1.0

### ISSUE THREAD

**Issue by Ks89** [qdouble/angular-webpack2-starter#205]
I suggest to update istanbul-instrumenter-loader, because now you are using 0.2.0.

**Comment by qdouble** [comment]
@Ks89 it throws errors when updating, a PR would be welcome.

**Comment by Ks89** [comment]
Related to this https://github.com/SitePen/remap-istanbul/issues/96

Two dependencies are ok, but we must wait another update of Karma-coverage-istanbul

**Comment by Ks89** [comment]
now all plugins are ok.
Tested on a personal project.

Theoretically, It should be possibile to use istanbul-instrumenter-loader 1.x.x also with this project.
