### ISSUE TITLE
Vendor dlls generated but then error - not exists

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#206]
When I add markerclusterer.js or jquery.js into the MY_VENDOR_DLLS, they are loaded in to vendor.dll.js but in browser I'm getting error that they are undefined.

When I import them directly via index.html, they works correctly.

Can somebody tell me what I'm doing wrong? Thank you for yours advice

**EDIT**

I noticed also when I import it directly in main.browser.ts,  - it also start to work - `import './lib/markerclusterer';`

So I'm not sure why it does not work via webpack dlls.

**Comment by qdouble** [comment]
could you link to repo?

**Comment by qdouble** [comment]
closing for now, will possibly re-open if I see the problem reproduced.
