### ISSUE TITLE
yarn build:aot fails

### ISSUE THREAD

**Issue by ricricucit** [qdouble/angular-webpack2-starter#207]
Trying to run `yarn build:aot` from branch _no-universal-support_ fails.
- - - 
Error Message:

````
ERROR in ./src/main.browser.aot.ts
Module not found: Error: Can't resolve './compiled/src/app/app.module.ngfactory' in '/Applications/MAMP/htdocs/giveaways/src'
 @ ./src/main.browser.aot.ts 6:29-79

ERROR in [default] /Applications/MAMP/htdocs/giveaways/src/main.browser.aot.ts:7:35
Cannot find module './compiled/src/app/app.module.ngfactory'.

Couldn't parse bundle asset "/Applications/MAMP/htdocs/giveaways/dist/client/index.js".
````

- - -
I didn't yet look into this issue, just wanted to report it.

**Comment by inzerceubytovani** [comment]
From readme:

To create AOT version, run yarn run compile. This will compile and build script. Then you can use yarn run prodserver to see to serve files. Do not use build:aot directly unless you have already compiled. Use yarn run compile instead, it compiles and builds:aot

**Comment by helzgate** [comment]
I was using typescript v2.1.1.  I downgraded to version 2.0.10 just like the current version qdouble is using and now i'm seeing errors I should have been fixing that for some reason 2.1.1 was skipping over.  After fixing the errors 2.1.1 was apparently ignoring, everything compiles fine now.

**Comment by DzmitryShylovich** [comment]
angular doesn't support ts 2.1+

**Comment by helzgate** [comment]
@DzmitryShylovich didn't know you were involved with qdouble's starter.  Is there anything you aren't involved with? lol
