### ISSUE TITLE
Import css (none sass) file

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#208]
I found that import css file into sass file is not allowed yet by default.  So I'm not sure where to import custom css files from 3rd party libraries (which has no sass files) to prevent import them to index.html. I found out solution to create new css file and import these libraries there. Somebody using better solution?

**Comment by Tuizi** [comment]
you can actually import a css file into a SASS file. I do that on my project using this starter.
I use the third party **PrimeNG** which come with a css file only (no sass, no less) and I import it by adding
`@import 'primeng/resources/primeng';` in `src / app / styles.scss` file.

PrimeNG is in node_modules and the css file is `node_modules/primeng/ressources/primeng.css`
