### ISSUE TITLE
scss "you may need an appropriate loader"

### ISSUE THREAD

**Issue by j3ddesign** [qdouble/angular-webpack2-starter#209]
I'm just in the process of switching over to this repo, however have run into a strange problem.

Even though in all of my components, my `styleUrls` point to the .css files, I get console warnings that I may need an appropriate loader for .scss

```
Module parse failed: <path-to-my-component>\my-component.component.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '../../../../variables';
| 
| :host {
 @ ./src/app/wrapper/+dashboard async ^\.\/.*$
 @ ./src/app/wrapper/+dashboard/dashboard.service.ts
 @ ./src/app/wrapper/+dashboard/dashboard.module.ts
 @ ./src/app/app.routing.ts
 @ ./src/app/app.imports.ts
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main
```

I've checked the webpack configs and dont see any mention of even resolving .scss files so I'm really unsure as to where to solve this. I also noticed it didn't happen with the initial clone's couple of scss files so I have no idea why mine would be different.

Just for clarification, this is an example of my styleUrls ` styleUrls: ['./my-component.component.css'],`

**Comment by DzmitryShylovich** [comment]
what branch do u use?

**Comment by j3ddesign** [comment]
non universal material 
https://github.com/qdouble/angular-webpack2-starter/tree/no-universal-support

**Comment by DzmitryShylovich** [comment]
> '../../../../variables'
is this your own file?

If so I think u need to add it here using `--include-path` https://github.com/qdouble/angular-webpack2-starter/blob/master/package.json#L56

**Comment by j3ddesign** [comment]
It's my own file, yeah. It's at the root of app/ - I had figured that'd be covered, as it's in the same place as it is in the starter (the file I took that error log from is just that far nested)

**Comment by DzmitryShylovich** [comment]
does it work without `@import`?

**Comment by j3ddesign** [comment]
I just checked some other logs to see if they all revolve around the @variables import, however I have a few that don't call the `@variables` file that are erroring, too.

```Module parse failed: E:\Layer1\layerone-front\src\app\wrapper\+dashboard\cards\twitch-chat\twitch-chat.component.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| :host {
|   display:inline-block;
|   margin:5px;
 @ ./src/app/wrapper/+dashboard async ^\.\/.*$
 @ ./src/app/wrapper/+dashboard/dashboard.service.ts
 @ ./src/app/wrapper/+dashboard/dashboard.module.ts
 @ ./src/app/app.routing.ts
 @ ./src/app/app.imports.ts
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main
```

**Comment by j3ddesign** [comment]
It's almost as if its trying to parse scss as css (looking at :host and @variables) - I just can't figure out why

**Comment by qdouble** [comment]
it's giving you scss warning when trying to import as css file?

**Comment by j3ddesign** [comment]
yep, that's what it seems.

**Comment by j3ddesign** [comment]
I've just gone and created a secondary clone of this to try and reproduce the issue, and I can't, so I can only assume somewhere I've got something being strange. I'm going to close this for now, as I think it's an issue with my side (Though I can't imagine what, I'm only importing css files)

If I find the cause, and it is something from this repo, I'll add a comment here :)
