### ISSUE TITLE
Integrate AngularClass/angular2-idle-preload for idle-preloading lazy loaded routes ?

### ISSUE THREAD

**Issue by Tuizi** [qdouble/angular-webpack2-starter#211]
I use that in my project base on this starter and it works well, it could be interesting to add this module as part of the starter?

https://github.com/AngularClass/angular2-idle-preload

**Comment by qdouble** [comment]
The description on their page is a bit unclear, what's the common use case of this?

**Comment by Tuizi** [comment]
It's using the famous new requestIdleCallback method (use fallback in case of browser not supporting the method)

When using the `preloadAllModule` (the actual configuration of this starter), Angular will load all lazy routes asap, and could delay the initial user interaction for the user. With `requestIdlePreload`, Angular will load lazy routes only when the browser is ready and can process new file. This is a very new popular API, very good for web performance and also for user experience.

https://developer.mozilla.org/fr/docs/Web/API/Window/requestIdleCallback
https://aerotwist.com/blog/when-everything-is-important-nothing-is/

**Comment by qdouble** [comment]
okay cool, I'll look into adding it. Going to be making a lot of changes to this repo soon, so I'll check this out after those changes

**Comment by Tuizi** [comment]
I can do the PR if you need some help, it's basically 2 or 3 lines of code. But no rush yes, later after the next version :)

**Comment by qdouble** [comment]
@Tuizi okay, cool... the PR will be welcome after we try to switch over to ngtools
