### ISSUE TITLE
[Question] How to add third party via npm (PrismJS)

### ISSUE THREAD

**Issue by mildful** [qdouble/angular-webpack2-starter#212]
I'm trying to do a very simple thing but I can't get it work so I'm coming here to ask some help.

I just want to add PrismJS to my libraries. 

I have installed the library via `npm i -D primjs`, then I've added it to the vendor dlls in constants.js : 
```
exports.MY_VENDOR_DLLS = [
  // list vendors that you want to be included in your dlls files
  // this will speed up initial dev server build and incremental builds.
  // Be sure to run `npm run build:dll` if you make changes to this array.
  'prismjs'
]
```

But I can't import it: `import Prism from 'prismjs';` (Cannot find module prismjs).

PrismJS have been successfully added to `dll/vendor.dll.js` but the module cannot be found by webpack and my IDE. 

`MY_VENDOR_DLLS` are simply added to `webpackConfig.entry.vendor`, I don't unnderstand what I'm doing wrong. I4ve also tried with differents paths like `prismjs/prism.js`, `prismjs/components/core.js` etc.

What am I doing wrong ?

**Comment by DzmitryShylovich** [comment]
> But I can't import it: import Prism from 'prismjs'; (Cannot find module prismjs).

did u install typings?

**Comment by mildful** [comment]
`typings search prism` returns:

```
NAME              SOURCE HOMEPAGE                                   DESCRIPTION VERSIONS UPDATED
prismjs           dt     http://prismjs.com/                                    1        2016-05-10T00:29:10.000Z
vortex-web-client dt     http://www.prismtech.com/vortex/vortex-web             1        2016-05-10T00:29:10.000Z
```

so I've tried to `typings install prismjs --save` but it can't find it on the registry.

Also, I've tried to debug `Prism` after imported it but it was undefined. Typings are just useful to map on typescript right ? Even if I do not import typings my console.log must shows me something that is not undefined ?

**Comment by DzmitryShylovich** [comment]
https://www.npmjs.com/package/@types/prismjs

**Comment by mildful** [comment]
Okay, I need to read more documentation about @types and typings. This isn't clear to my mind.

I've installed the package and I'm trying to import it via `import Prism from '@types/prismjs';` but I get another error :

`File '.../node_modules/@types/prismjs/index.d.ts' is not a module.`

Of course, index.d.ts is here, I've also tried to import from 'prisnjs', just like before. I'm going to read some things on typings. Thanks a lot for your help.

**Comment by mildful** [comment]
Okay so I can't get it worked.

There was a difference between the prismjs's version of package.json and @types. [Reading this](http://stackoverflow.com/a/38444504/5542588) I'm now using 1.4.x both with npm and ts.

error message : `File '.../node_modules/@types/prismjs/index.d.ts' is not a module.`

**Comment by qdouble** [comment]
There's nothing particularly tricky about installing @types unless the package that you're installing is broken, so I'll close this issue for now as I don't think that it's a problem with this repo.
