### ISSUE TITLE
helpful note for existing projects merge steps

### ISSUE THREAD

**Issue by bf0** [qdouble/angular-webpack2-starter#213]
In step 4 of the [Recommended Steps for Merging Starter into Existing Project](https://github.com/qdouble/angular-webpack2-starter/wiki/Recommended-Steps-for-Merging-Starter-into-Existing-Project) guide, I had to merge with `--allow-unrelated-histories`

```
$ git merge starter/master
fatal: refusing to merge unrelated histories
$ git merge starter/master --allow-unrelated-histories
Auto-merging tslint.json
... merge procedes ...
```

A note that this may be necessary could help others who run into the same thing.

**Comment by qdouble** [comment]
Thanks, I added that to the instructions.
