### ISSUE TITLE
Performance attributes of repo

### ISSUE THREAD

**Issue by Splaktar** [qdouble/angular-webpack2-starter#216]
Since it seems like the main purpose of this seed/starter is Angular Universal, Webpack2, and AOT; I feel like the README should include some performance stats of the current build of the starter. Since it does not have this info yet, I wanted to share what I'm seeing on my machine atm.

* Times listed for No throttling / Regular 3G.

## Dev Mode
`npm start`

- 29 requests
- 5.8 MB
- 1300ms / 66000ms DOMContentLoaded
- 1350ms / 66000ms load

## Universal
`npm run universal`

- 16 requests
- 363 KB
- 928ms / 4480ms DOMContentLoaded
- 973ms / 5020ms load

## AOT mode
`npm run compile` + `npm run prodserver`

- 16 requests
- 301 KB
- 432ms / 3530ms DOMContentLoaded
- 495ms / 3930ms load

## Universal + AOT
`npm run universal:aot` or `npm run compile:universal`+ `npm run prodserver`

- 16 requests
- 392 KB
- 494ms / 4410ms DOMContentLoaded
- 535ms / 5030ms load

Tests run on

- Chrome 57.0.2951.0 canary (64-bit)
- MacBook Pro (Retina, 15-inch, Mid 2014)
- 2.8 GHz Intel Core i7
- 16 GB 1600 MHz DDR3
- OS X El Capitan 10.11.6 (15G1212)
- NodeJS 6.7.0

Now I know that Universal and AOT are still undergoing a lot of breaking changes and needed improvements, but I found it a little odd that the combination was slower than the build with AOT alone.

Since the angular-cli isn't supporting Universal + AOT yet, I was looking to find a solid seed for Universal, AOT, Webpack2, Material2, etc. and this one seems to be the closest that I can find which isn't broken. 

But with the numbers above, I wonder if I should even bother with Universal at this point. Then I thought, well it should help get that initial paint a lot faster. But on anything 3G+, the time between initial paint and interactivity is under 50ms and isn't even noticeable. If I drop down to Regular 2G, then I do see the initial DOM loaded for about 2s before the page is interactive and rendered properly. 

Perhaps part of this issue is that the app doesn't have an appShell (it's just a white `Loading...` page), but either way I'm not sure that I should go to the extra trouble of running a NodeJS server for Universal at this point rather than just hosting a client-only app in Firebase. SEO is something that I really need, but I'm not convinced that Universal will work properly here and deliver the desired results.

Maybe I should just stick with AOT until Universal gets better support from Angular core (in progress). It's nice that this seed makes that a well supported option. Thanks for your hard work and sharing what's working for you!

PS. This is the first time I've tried this repo, please let me know if I should be running different commands for one of the combinations. I tried to go by what the README suggested.

**Comment by qdouble** [comment]
@Splaktar you're correct in the fact that Universal is underperforming, but that's mostly because we're only spitting it out in JIT mode instead AOT. Personally, I've been leaning towards using AOT only in my real projects mostly because of the current incompatibility with Material. Until they fully transfer Universal to the main angular branch and start testing against it, it's support will lag behind the rest of angular. 

There does appear to be ways to get AOT running with Universal (at least there seemed to be a few weeks ago), I just haven't gotten around to it yet as I will have to make a ton of changes and I haven't been using Universal in my real project, so it isn't a top priority for me. Universal is stuck on Angular 2.1.2 as far as compatibility and you have to do some hacks to get it to work with AOT, so the current support there is not great.

**Comment by colinskow** [comment]
@Splaktar that's some great data! It would be awesome if you could write a benchmark script (using perhaps Protractor) that automatically generates a report like that. Add it as a command in the `package.json` and submit a pull request.

**Comment by Splaktar** [comment]
Unfortunately, that is not something that I have cycles to work on at this time. I'm also not sure how to capture the correct perf/size metrics with Protractor. I am going with a similar approach to that mentioned above, just using AOT and waiting for Universal to be merged into core and stabilized.

**Comment by keenkiran** [comment]
@qdouble Now that Universal is part of Angular 4, is this issue still relevant ?

**Comment by qdouble** [comment]
@keenkiran actually, I'll close. Perf is such a specific element that if we are not comparing apples to apples it does become a bit irrelevant.
