### ISSUE TITLE
Navigation event called twice

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#223]
I noticed that on nav change the event is called twice. I found out this is because of this issue https://github.com/ngrx/router-store/issues/29

So if anyone has same problem all you have to do is comment out or remove RouterStoreModule.connectRouter(), from APP_IMPORTS Array in app.imports.ts file (of course if you don't use that ngstore routerStore module).

This is not bug of this starter but I put it here for anyone struggling with same issue. It was lucky that I found reason of that behaviour.

**Comment by qdouble** [comment]
@inzerceubytovani is this on lazy loading or event on any component?

**Comment by inzerceubytovani** [comment]
Problem appears without lazy with any component, I did not test it with lazy loading.
