### ISSUE TITLE
Lazy loading hide and show

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#225]
I noticed when I used lazy loading with universal, server respond me with correctly displayed site, but then that content dissapears and appears in moment again when it was switched to front generated view. I notice same issue happens in lazy load preview in this starter pack. I understand that it because there is a delay between site is loaded and lazy loaded part is loaded - that's the time space. But I'm interested If there is a way to make it without that disappear action. Due to that issue I stopped using lazy loading and return to simple components routes.

**Comment by qdouble** [comment]
@inzerceubytovani are those lazy loaded routes listed in your https://github.com/qdouble/angular-webpack2-starter/blob/master/src/server.routes.ts ?

**Comment by inzerceubytovani** [comment]
Yes they are, as I sad server return lazy loaded content correctly but then client reproceed lazy loading and that imo malé that hide/show jump
