### ISSUE TITLE
Feature Request: Use Rollup for Treeshaking

### ISSUE THREAD

**Issue by fmoessle** [qdouble/angular-webpack2-starter#228]
Hi qdouble,

did you thought about using rollup for treeshaking in this starter?

I am also excited about the integration of angular/material@2.0.0-beta.1 :)

Greetings from Germany!

**Comment by DzmitryShylovich** [comment]
Lazy loading doesn't work with rollup

**Comment by qdouble** [comment]
Yeah, I've thought about this, but have no idea how easy it would be to transition back and forth. Sure there is no lazy loading, but you don't need to use lazy loading on smaller apps. Maybe I'll attempt it one day.

**Comment by colinskow** [comment]
I've got tree shaking working on the vendor chunk (using the `CommonsChunkPlugin`) with Webpack2 here:

https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js#L193

Rollup is not necessary with Webpack2.

**Comment by colinskow** [comment]
This automatically extracts any dependencies from the main entry point that are inside `node_modules` to the vendor chunk and tree shakes them.

**Comment by qdouble** [comment]
@colinskow yes, I understand that webpack can treeshake, however rollup is still supposed to be able to produce smaller/faster bundles by the way it reduces everything to one module.
