### ISSUE TITLE
Universal+AOT compilation failed

### ISSUE THREAD

**Issue by fdambrosio** [qdouble/angular-webpack2-starter#230]
I'm using this starter kit, with 
npm 4.0.5
node v7.2.1 
typescript 2.1.4

when use `yarn start` or `yarn run compile` my app works .

But I can't compile with universal+aot because there's errors about protractor

With `yarn run universal:aot` I have this errors: 

```
> ngc -p tsconfig.aot.universal.json

Error: Error at /app/node_modules/protractor/built/locators.d.ts:4:39: Cannot find name 'By'.
Error at /app/node_modules/protractor/built/locators.d.ts:5:27: Cannot find name 'By'.
Error at /app/node_modules/protractor/built/locators.d.ts:6:25: Cannot find name 'By'.
Error at /app/node_modules/protractor/built/locators.d.ts:7:37: Cannot find name 'By'.
Error at /app/node_modules/protractor/built/locators.d.ts:8:25: Cannot find name 'By'.
Error at /app/node_modules/protractor/built/locators.d.ts:9:29: Cannot find name 'By'.

Error at /app/node_modules/protractor/built/browser.d.ts:2:76: Module ''selenium-webdriver'' has no exported member 'Options'.
Error at /app/node_modules/protractor/built/browser.d.ts:2:116: Module ''selenium-webdriver'' has no exported member 'TargetLocator'.
    at check (/app/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/app/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /app/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Compilation failed
```

**Comment by qdouble** [comment]
It's already mentioned in the other that Universal isn't working in AOT mode... I probably be making many update to the Universal branches until angular 4 where Universal is merged into angular core: https://github.com/angular/angular/issues/13822 

Right now, with Universal not keeping up to date with angular, it's not really useable in my real project and I've just been sticking to using AOT and lazy loading. If anyone wants to submit any PR's to Universal fixes in the meantime, I'll merge them.

**Comment by DzmitryShylovich** [comment]
> it's not really useable in my real project 

even googlers say it's not usable :)
