### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by eruecco87** [qdouble/angular-webpack2-starter#233]
The ENV constant gets set from `process.env.npm_lifecycle_event` to `ENV: PROD ? JSON.stringify('production') : JSON.stringify('development')` in the webpack config.

Is there a way that I could run  a command such as 'npm run build:qa' and have the ENV constant set to 'QA';

In my particular setup we manage more than the main two environments, so different API urls are used for those environments and can't manage to find a way to implement that.

**Comment by qdouble** [comment]
You'd just have to add more scripts in the package json file and then add the constants to the webpack config if you wanted to do that
