### ISSUE TITLE
hammerjs doesnt seem to be working for md-slider

### ISSUE THREAD

**Issue by futbotism** [qdouble/angular-webpack2-starter#234]
i have installed a fresh version of the webpack starter and added 

`<md-slider min="1" max="5" step="0.5" value="1.5"></md-slider>`

the drag feature doesnt seem to be working, i think this is related to hammerjs.

In the docs for material 2 it says,
If you want to include HammerJS from npm, you can install it:

`npm install --save hammerjs `
`npm install --save-dev @types/hammerjs`

Import HammerJS on your app's module.

`src/app/app.module.ts`

`import 'hammerjs';

`Finally, you need to add hammerjs to the types section of your tsconfig.json file:

`{
  "compilerOptions": {
    "types": [
      "hammerjs"
    ]
  }
}`

I cant see any of these setting in the tsconfig or the import statement in app module

**Comment by qdouble** [comment]
I haven't tried to use the slider yet myself, have you tried to use it with any other repo, is that a particular problem with this repo or just material itself?

**Comment by futbotism** [comment]
i think the issue is with this repo, i have used it properly with the angularclass webpack starter (https://github.com/AngularClass/angular2-webpack-starter)

specifically i think the issue is with the step of adding the "types": [ "hammerjs" ] to the tsconfig (as specified in the material get started guide https://material.angular.io/guide/getting-started), 

both times i added it in i got an exception thrown in the node console.

**Comment by qdouble** [comment]
@futbotism you don't need to add types to the tsconfig as it's already importing the whole folder, you're probably getting an error for importing it twice

**Comment by qdouble** [comment]
If you're using the material branches, hammerjs is already in the index html file:
It copies it here: https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L102
Then references it here: https://github.com/qdouble/angular-webpack2-starter/blob/master/src/index.html#L21

However, if you're using the minimal branch or are just trying to load it a different way, make sure you also put it in the vendor dlls if you're going to bring it in your project as an import: https://github.com/qdouble/angular-webpack2-starter/blob/master/constants.js#L65
