### ISSUE TITLE
Vendor DLL is built but can't be found by app.

### ISSUE THREAD

**Issue by Ecafracs** [qdouble/angular-webpack2-starter#237]
I'm having problems with including a vendor DLL.  I've added the package name (tone) to MY_VENDOR_DLLS and everything builds fine, but when I load the app in the browser, it can't seem to find it:
error_handler.js:49 EXCEPTION: Uncaught (in promise): ReferenceError: Tone is not defined

I suspected the issue was that the tone package has the built library under the subdirectory "build/", but changing the MY_VENDOR_DLLS entry to 'tone/build/tone.js' didn't work.  Running yarn run build:dlls still works, but the app still can't find it.

**Comment by qdouble** [comment]
Not sure if there is anything in particular I can do, if you're getting that it just means that webpack is not finding it for some reason
