### ISSUE TITLE
yarn.lock should be in the repository

### ISSUE THREAD

**Issue by Tuizi** [qdouble/angular-webpack2-starter#238]
It's an advise from yarnpkg themselves.

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

**Comment by qdouble** [comment]
@Tuizi 1) It'd be headache to have a yarn.lock for different branches, 2)If your project dependencies start to diverge from the starter, then you'd have be pulling in a conflicting yarn.lock file when cherry-picking updates

**Comment by Tuizi** [comment]
Oh yes you are right. Maybe not a good idea for starter :)
