### ISSUE TITLE
Cant import bootstrap

### ISSUE THREAD

**Issue by HristoKolev** [qdouble/angular-webpack2-starter#239]
Hi, I'm using the minimal version of this starter and since I updated today I can't get bootstrap to load properly. 

Here is the error I get: https://i.imgur.com/PN2nhdC.png

I used to get around that by doing this: 

```
import * as $ from 'jquery';
window['jQuery'] = $;

import 'bootstrap/dist/js/bootstrap.js'
```

But that no longer works. I tried the webpack ProvidePlugin but couldn't get it to work either.

Any suggestions?

**Comment by inzerceubytovani** [comment]
I struggled with this too and I started to use workaround with importing jquery directly in html head tag. Not ideal, but works. Hope that helps.

**Comment by qdouble** [comment]
You may want to check the wiki's in some of the other angular repos or their github issues for solutions... I don't touch jquery, so don't remember the workarounds off the top of my head, but I've saw them before.
