### ISSUE TITLE
Debugging is a challenge - many error messages are unhelpful

### ISSUE THREAD

**Issue by jongunter** [qdouble/angular-webpack2-starter#240]
I'm running into issues when I have errors in my components. If I have an error in a component TS file, I often get unhelpful console messages like this (they usually involve errors with the property `stack`):
```
 Cannot set property stack of [object Object] which has only a getter
````
In angular cli projects, stack traces of component errors use source maps to give a specific error in the TS file. Here, I don't even know which file is causing the error. I end up having to comment out methods in my components until I find the one that stops the error.

**Comment by DzmitryShylovich** [comment]
it's a zone.js issue. you need 0.74 or 0.76 version

**Comment by jongunter** [comment]
That did it. Thanks :) 

Should the repo's `package.json` be updated?
