### ISSUE TITLE
Dlls injection not working in server:prod

### ISSUE THREAD

**Issue by cuznerdexter** [qdouble/angular-webpack2-starter#242]
This code in index.html
```
<%= '<' %>script src="/polyfill.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
<%= '<' %>script src="/vendor.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
```

works fine using 'yarn start'
but index page is broken when using 'yarn run server:prod'

The code is ignored and just displays as text on page.

**Comment by qdouble** [comment]
The dlls stuff is for dev only and is not supposed to work in production
