### ISSUE TITLE
Problems after updates in last days

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#243]
I decided to make updates and I hit on some problems:

**1. awesome-typescript-loader 3.0.0-beta.17**
Although it proceed to markable speed up during build (during developing with dev server, time space between Invalid detection and rebuild process disappeared), when it's used with universal, this problem appears - https://github.com/s-panferov/awesome-typescript-loader/issues/323

**2. t.map is not a function during starting**
This error appears in universal console when I open browser with universal. I didn't find reason of this problem yet.

EDIT:

1. Fix should be released soon

2.  I found it that this message is exactly - ctorParameters.map is not a function.. - and it's because some plugins updates (like angular2-modal...) now needs new version of angular 2 (at least 2.3) but angular2 universal does not support this new versions yet. So solution was set up fixed versions of those plugins in package.json in angular2 until angular2 universal will not have support.

**Comment by inzerceubytovani** [comment]
1. FIXED

**Comment by ThomasKientz** [comment]
Hi,  @inzerceubytovani  

I got the same error : "ctorParameters.map is not a function". But I don't understand your solution. 

I'm trying to use the AngularFire module.

Which plugins must have fixed versions in package.json ? 

Thanks

**Comment by inzerceubytovani** [comment]
You have to find older version of modules which generate this error and use them.
