### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by ngFor** [qdouble/angular-webpack2-starter#246]
Hi @qdouble , thanks for all the work you've put into this so far. 

The package.json says `"license": "Apache-2.0",`, while the repo README also says "MIT License". I was hoping you could clarify the following:

If I hypothetically use this starter for it's build system to start out with, and customize it as necessary, while creating a commercial product, what obligations do I have?

Thanks again.

**Comment by qdouble** [comment]
I mean, if you create a PR, we can set the licensing properly. I mostly grabbed what I saw on other projects as far as that, but whatever most projects like this are supposed to use is fine with me.

**Comment by ngFor** [comment]
I'm not even really sure about the differences between those two licenses. I guess I'm mainly wondering if I use this at my job, in some corporate repo, do I have to keep the license from your repo in mine? I'm basically stripping out all the application logic and just using the bare minimum build system.

**Comment by qdouble** [comment]
@ngFor you should be fine, this it's just a starter config that you can use and change for your own purposes.
