### ISSUE TITLE
Lazy loading with AOT on Universal

### ISSUE THREAD

**Issue by inzerceubytovani** [qdouble/angular-webpack2-starter#249]
I tried to switch to lazy load. I'm already using AOT with universal. But with lazy loads, on server side  I got this error:

`Unhandled Promise rejection: No NgModule metadata found for '[object Object]'. ; Zone: angular ; Task: Promise.then ; Value: Error: No NgModule metadata found for '[object Object]'.
`

Front rendering happens without problems, but from universal server I did not get html response due that error.

Also when I try to use AOT with Lazy loading without universal, it works perfect.

Anyone has same problem and found a solution? Thanks

**Comment by tashoecraft** [comment]
@inzerceubytovani qdouble/angular-webpack2-starter#230

**Comment by qdouble** [comment]
closing for now, not touching Universal branch until Angular 4.0 is working with Universal Support
