### ISSUE TITLE
Lazy Loading without router

### ISSUE THREAD

**Issue by dschewchenko** [qdouble/angular-webpack2-starter#250]
Hi, @qdouble! Big thanx for your starter kit, it's awesome!
I'm using Universal in AOT mode with lazy loaded modules. It's working good =)
But, I have very big module on one page, I may to split it in 2 modules, but in one route(page)
1 - for main code
2 - for modal window, that opens by clicking on button. Only for users that want to edit something

How I can to lazily load modal window with its children components on click?
Something similar to [this](https://plnkr.co/edit/mgdBhKpCVI1LRQ2l81pC?p=info), but using your kit and for module.

P.S.: main code and modal window are in the same size of code (each 150KB gzipped)

**Comment by qdouble** [comment]
I can possibly look into your question when angular 4.0 is officially released with universal support, but I'm not really touching that branch anymore until then. Feel free to ask again around that time.
