### ISSUE TITLE
@types/jasmine causes fresh clone npm install to fail

### ISSUE THREAD

**Issue by mcescalante** [qdouble/angular-webpack2-starter#251]
@types/jasmine broke semver upstream and version `2.5.42` contains Typescript 2.1 definitions but Angular 2.x only officially supports up to Typescript 2.0.10, which is correctly used here. Because @types/jasmine uses `~` in package.json, when you run `npm install` you get version 2.5.42 or newer and the following output (selected):

```
ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:52 
    TS1005: '=' expected.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:38 
    TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:46 
    TS2304: Cannot find name 'keyof'.
```

`@types/jasmine` needs to be locked at `2.5.41` to successfully run `npm install` on a clean clone. Technically, bumping Typescript to 2.1.x would work but it will break a lot of stuff including AoT. Typescript 2.1 support is coming in Angular 4.x.

I would be happy to open a PR for this if you prefer.

**Comment by gruppjo** [comment]
I created a PR, in case you are interested: https://github.com/qdouble/angular-webpack2-starter/pull/259

But maybe it's not necessary. Are there any plans to revert this behavior in @types/jasmine? Do you know @mcescalante?

**Comment by mcescalante** [comment]
There aren't plans to revert this behavior as far as I know, so in my projects I've been locking `@types/jasmine` until Angular 4.x is stable - then we can bump to Typescript 2.1 and unlock `@types/jasmine`

**Comment by qdouble** [comment]
This shouldn't be an issue on the last update of the non-universal branch.
