### ISSUE TITLE
How to add font-awesome?

### ISSUE THREAD

**Issue by Ks89** [qdouble/angular-webpack2-starter#253]
Hi!
I have a simple question: how can I add font-awesome to this project?

Thank u.

**Comment by xuxinsheng** [comment]
1.import 'path/to/font-awesome.scss' into styles.scss
2.copy folder fonts into assets folder
3.add '$fa-font-path: 'assets/fonts';' to _variables.scss
4.run npm sass
5.rerun npm start
6.enjoy

**Comment by Matmo10** [comment]
@xuxinsheng Thanks man, I've been using font-awesome via a CDN but this is much better :)   Works great

**Comment by Ks89** [comment]
@xuxinsheng 
Thank u, but I have a problem.
I copied fonts by my self with ctrl+c and ctrl+v in assets but I couldn't see fonts.
So i tried to copy fonts using `new CopyWebpackPlugin([{ from: 'node_modules/font-awesome/fonts', to: 'src/assets' }])`, but I cannot see any icons, but only a square :(

I'm using no-universal-support branch and I'm receiving this warning in my console: 
`Failed to decode downloaded font: http://localhost:3000/fonts/fontawesome-webfont.ttf?v=4.7.0`

**Comment by Matmo10** [comment]
Heres what I did personally:

- Create a new npm script: `"copy-fa-fonts": "cp -r ./node_modules/font-awesome/fonts ./src/assets"` 
- Add this script to the beginning of your `sass` script, like so: `"sass": "npm run copy-fa-fonts && node-sass src -o src --include-path node_modules --output-style compressed -q"`
- Add `/src/assets/fonts/FontAwesome.*` and `/src/assets/fonts/fontawesome-*` to gitignore
- Run `npm run sass` once before developing.

**Comment by Ks89** [comment]
Still not working.
@Matmo10 I followed your procedure without success.

How did you import font-awesome in your project?

I tried adding into:
- src/app/styles.scss:       @import 'font-awesome/scss/font-awesome.scss';
- src/app/_variables.scss:     $fa-font-path: 'assets/fonts';

but I cannot see any icons, but only a square :(

**Comment by Matmo10** [comment]
In my styles.scss I have `@import '../../node_modules/font-awesome/scss/font-awesome';` and I did the same thing as you in _variables.scss.


Have you verified whether the font files are successfully copied into the assets folder?  You should see some network requests for one or some of those files when your app starts if you imported font-awesome successfully.

**Comment by Ks89** [comment]
Thank u for your answer.
I added `@import '../../node_modules/font-awesome/scss/font-awesome';` to styles.scss, but nothing is changed.

In my console I still receiving this warning: Failed to decode downloaded font: http://localhost:3000/fonts/fontawesome-webfont.woff2?v=4.7.0, but I have some network requests related to fonts that are ok.

And I cannot see any icons, but only a square.

I'm always trying with branch 'no-universal-support'

This is the result:
<img width="1493" alt="png" src="https://cloud.githubusercontent.com/assets/6057207/23344622/f4887936-fc7f-11e6-9544-10433e969a1e.png">

**Comment by Matmo10** [comment]
Try version `4.2.0` instead for the hell of it. That's the version I'm on.

**Comment by Matmo10** [comment]
I'm not sure :(
<img width="1391" alt="screen shot 2017-02-26 at 3 21 31 pm" src="https://cloud.githubusercontent.com/assets/2548215/23344787/6bfcc678-fc37-11e6-8d57-7dcf8d06e23f.png">

**Comment by xuxinsheng** [comment]
@Ks89 
You must copy font-awesome/fonts folder into assets or dist folder,then in the variables file declare the path!Actually this is a 404 error.

**Comment by Ks89** [comment]
> Oh,in the styles.scss, @import 'variables' must at the top line.

Probably, I was doing exactly the opposite thing :(

@xuxinsheng thank u, I'll try this evening

**Comment by Ks89** [comment]
> Oh,in the styles.scss, @import 'variables' must at the top line.

@xuxinsheng thank u, it worked

Issue closed XD
