### ISSUE TITLE
prodserver.js package dependency missing in production

### ISSUE THREAD

**Issue by laurianek** [qdouble/angular-webpack2-starter#254]
Hi,

Super nice project!

I just have a suggestion: move package `ip` from the `devdependencies` to `dependencies` in `package.json` since it's require by `contants.js` and therefore by `prodserver.js`. 
(Usually production server like heroku will only install `dependencies`).

Thank you

**Comment by qdouble** [comment]
Cool, I moved it here: https://github.com/qdouble/angular-webpack2-starter/commit/77f0567beae9848b997c27f565bfc04604996e9b
