### ISSUE TITLE
Universal to NonUniversal

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular-webpack2-starter#258]
Hello,
So i had been working on universal branch, since its useless right now to keep universal, i want to switch to non-universal, can u tell me how can i safely switch branches by merging codebase?

**Comment by qdouble** [comment]
Hey, the non universal branch is very similar... it just strips some stuff of the universal branch, if you create a temp branch based on the non-universal branch and copy over your main project files, it shouldn't be too difficult to get it to work
