### ISSUE TITLE
AOT output still imports from original source

### ISSUE THREAD

**Issue by woutervandergraaf** [qdouble/angular-webpack2-starter#261]
When I run `compile` and look at the generated file compiled/src/app/app.module.ngfactory.ts, I see that files are also imported from the src directory:

import * as import64 from './features/dashboard.component.ngfactory';
import * as import67 from '../../../src/app/features/dashboard.component';

Not all files are compiled, so it makes sense for those to be imported from their original location. But the example above looks wrong to me.

**Comment by qdouble** [comment]
I don't think this repo is doing anything to give behavior that isn't standard, if the ngfactory files come out different in other repos, let me know
