### ISSUE TITLE
Exception 'Cannot read property 'setGlobalVar' of null' caused by disableDebugTools()

### ISSUE THREAD

**Issue by alexthewilde** [qdouble/angular-webpack2-starter#263]
I'm running on the latest release of the `no-universal-support` branch with Angular `4.0.0-rc.1`. 

After creating a new production build, an error `Uncaught TypeError: Cannot read property 'setGlobalVar' of null` gets thrown when I open the app in the browser.

The error is caused by calling `disableDebugTools()` in `environment.ts`. Commenting out this method makes the error go away.

**Comment by mircowidmer** [comment]
This also happens with Angular 4.0.0 and webpack 2.3.1. The workaround @alexthewilde suggested works, although it's not clear to me what the implications are.

Digging a little bit in the source seems to indicate, that getDOM() returns null.
```
function disableDebugTools() {
    getDOM().setGlobalVar(PROFILER_GLOBAL_NAME, null);
}
```

**Comment by qdouble** [comment]
I don't see that issue with the updates I made the other day, but if it's still a problem, let me know

**Comment by tashoecraft** [comment]
I'm still seeing this on the latest off branch no-universal-support

**Comment by qdouble** [comment]
@tashoecraft how do you reproduce it exactly?

**Comment by larrybek** [comment]
Its reproduced only in production version for me.

**Comment by tashoecraft** [comment]
@qdouble I merged into my own project and was still seeing it as an issue. So unfortunately I don't have a way to showcase the reproduction. Could you link to the PR that you said fixed it? I'll take a look through and try to diagnose it on my end.

**Comment by qdouble** [comment]
@tashoecraft I never really noticed the issue, but wasn't testing for it before, this is the most recent package update where I didn't notice the problem after: https://github.com/qdouble/angular-webpack2-starter/commit/d6bc2304b66fd854c6b3901593c30d823b15d8dc

**Comment by fshchudlo** [comment]
@qdouble Maybe this can help.
I can reproduce this error when I building app with `build:prod:e2e` command. 
But when I use `build:aot:prod:e2e` there's no errors.

**Comment by fdambrosio** [comment]
I can reproduce this error, the fix(webui) works, it's safe to comment //disableDebugTools(); ?

**Comment by qdouble** [comment]
@fdambrosio yes, it is, I had already commented that out in the Universal branches, I just forgot to do it in the non-universal branches. I updated those now: https://github.com/qdouble/angular-webpack2-starter/commit/6539e782bfa2e5ef787a5a7a9a8fe575265b0bfd

**Comment by bodixon** [comment]
I've been just migrating angular from 2.4 to 4.0, and got the same error.

And I found workaround, but I didn't have time to figure out why it helps. So here is fix which helped for me:

```
const platform: PlatformRef = platformBrowserDynamic([
    { provide: APP_CONFIG, useValue: appConfig }
]);

// this function has to be invoked after platformBrowserDynamic
if (isProduction) {
    disableDebugTools();
}
```
