### ISSUE TITLE
assets not loaded in universal

### ISSUE THREAD

**Issue by alastair-todd** [qdouble/angular-webpack2-starter#271]
I have cloned the material + universal tree (why material dependency btw?)

Running the universal build, the following assets all 404, but I can see them in the dist/folder
﻿
`yarn run universal`

> (index):9 GET http://localhost:8000/styles.css 
> (index):10 GET http://localhost:8000/main.css 
> (index):377 GET http://localhost:8000/index.js 
> (index):377 GET http://localhost:8000/index.js 
> ﻿

`​yarn start
`
serves all assets fine

I do note the universal command reports "listening on http://169.254.244.89:8000" the ip of which looks suspicious. should be 0.0.0.0 ?

**Comment by qdouble** [comment]
As mention in some of the other closed issues, universal will be updated when it's stable in angular 4...it was unstable in 2x

**Comment by alastair-todd** [comment]
@qdouble maybe leave one open and/or remove the duff code or put in big bold letters 'Don't waste your time and energy on Universal in this repo'. What about the stated project goals?

**Comment by qdouble** [comment]
@alastair-todd I can leave this one, open... there were a bunch of other ones that I closed. Universal was basically breaking after ever new update of Angular and was totally unstable, so it wasn't very useable in production...so I stopped using and updating it. Once it's stable, I'll update those branches, but it's just like chasing your tail at this point. 

At ng-conf they say they should be releasing docs on using it with ng4, so hopefully I'll be able to update it once that's stable (I'm guessing angular 4.1).

**Comment by zmnv** [comment]
Any solutions?

**Comment by qdouble** [comment]
@zmnv I'm going to start playing around with updating the universal branches to 4.0 today, but I think they said material won't be fully compatible with it until 4.1 or later

**Comment by zmnv** [comment]
@qdouble material isnt important for branch bootrap + universal. 
Now `yarn run universal` doesnt work correctrly :(

**Comment by qdouble** [comment]
@alastair-todd  @zmnv I just merged an update of the main branch to angular 4.1. There still seems to be compatibility issues with material and animations, but it works fine otherwise. 

Hopefully it won't be long until everything is working smooth... I'll try to start back making updates more often, but PRs are welcome.

**Comment by qdouble** [comment]
@zmnv just updated the bootstrap branch, everything seems to work fine. Closing this issue, the main material universal branch should be fine once they update material to be compatible.
