### ISSUE TITLE
hmr breaks after module change

### ISSUE THREAD

**Issue by ShankarSumanth** [qdouble/angular-webpack2-starter#274]
Hey, I think the master branch requires a few more refinements.  I was testing persistent state with hmr and the app breaks. 

* Steps to reproduce
1. Start the app using `yarn run start:hmr` . 
2. Go to `localhost:3000`
3. The app loads the Dashboard page/component
4. make a simple change in the dashboard.html (like changing Welcome to My Angular).

Actual Output : selector `my-app` did not match any output.
Expected Output : the app loads via hmr and does not throw error.

<img width="1275" alt="screen shot 2017-05-06 at 21 13 32" src="https://cloud.githubusercontent.com/assets/15848680/25775261/5d8a54de-32a1-11e7-880a-05c56980b0e3.png">

**Comment by qdouble** [comment]
It should be fixed now: https://github.com/qdouble/angular-webpack2-starter/commit/daedd8076ee47dee8b643002901b48bc73b9a3d7

**Comment by ShankarSumanth** [comment]
Yes, It's working now. Thanks a lot 👍
