### ISSUE TITLE
Lazy load route/ lazy reducer/ hmr state persistence

### ISSUE THREAD

**Issue by ShankarSumanth** [qdouble/angular-webpack2-starter#276]
Hi @qdouble 

I am running into issues when I try to add a reducer for a lazy loaded route which should persist state for hmr. 

# Goals 

1. Add state/reducer to lazy loaded route
2. The reducer should be added only when the route is loaded
3. The app state should be persistent when changes made to lazy loaded route  in hmr mode.

# WIP
I am trying to implement the suggestions from (@ngrx/store)  [197](https://github.com/ngrx/store/issues/197) and combine it with this repo.
 
|What was working| What is breaking|
| :-------------: |:-------------:|
| Whenever I navigate to the lazy loaded route, the rootReducer was called| Now because of my changes to add lazy reducer this is breaking|

Since this breaks, the state on the lazy loaded route will not be persisted when changes are made. I am not sure what changes I need to make to fix this. 
The reducer on the lazy loaded route does not go through the root reducer path at all. (Like when I update store from dashboard page) somehow it bypasses the whole workflow and this I think is the root of the issue.

It would be great if you could help me out with this. I can send a PR for this. 
I think it would be great example if we could add this to the repo.

**Comment by qdouble** [comment]
I haven't played around with lazy loading reducers yet. I may try to play around with it, but if you come up with a solution before I add it, feel free to submit a PR.

**Comment by ShankarSumanth** [comment]
merged with #277
