### ISSUE TITLE
Bootstrap and Universal Branch faling to run for prod

### ISSUE THREAD

**Issue by Sangameshr** [qdouble/angular-webpack2-starter#281]
Hi,

I am trying to run the "Bootstrap and Universal Branch" for prod build with command "npm run server:prod" and it fails. Whereas "npm run server:dev" works fine. Same is the case with master branch. 

Am I missing something?

Error message:
"npm ERR! Failed at the angular-webpack2-starter@3.0.0 server:prod script 'npm-run-all -p -r watch:prod prodserver'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -p -r watch:prod prodserver
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above."

Thanks,
Sanga

**Comment by qdouble** [comment]
should be fixed now, may have accidentally deleted that part in a recent update: https://github.com/qdouble/angular-webpack2-starter/commit/a5077683c7ce736fb38b0a5af87c901fc2d86ee5

**Comment by Sangameshr** [comment]
thanks, it resolved after adding the missing line.
