### ISSUE TITLE
dev sass:watch

### ISSUE THREAD

**Issue by akalitenya** [qdouble/angular-webpack2-starter#282]
no-universal-support branch
I don't know is it issue or not.
After running `yarn start` When i modify styles.scss - it does not look like styles.css changes automatically without running `sass` explicitly.

maybe in package.json
```
"server:dev": "npm run webdev",
```
should be
```
"server:dev": "npm-run-all -p -r webdev sass:watch",
```
? (works for me)

**Comment by qdouble** [comment]
Hey, yes...thanks for pointing it out...I've updated it: https://github.com/qdouble/angular-webpack2-starter/commit/79f17d3b51e6e1f8dc258b385510da5ebc05053b
