### ISSUE TITLE
[Question] Bootstrap platformBrowser vs platformBrowserDynamic in AOT

### ISSUE THREAD

**Issue by kclercR310** [qdouble/angular-webpack2-starter#286]
I see in the main.browser.ts the app is bootstrapped with the dynamic method of Angular.

For AOT should it not be with the 'static' method of Angular?
something like: `platformBrowser().bootstrapModuleFactory(AppModuleFactory)`

**Comment by qdouble** [comment]
@kclercR310 I don't think you have to do it when using the webtools aot plugin, but test it and let me know if there is a difference

**Comment by kclercR310** [comment]
@qdouble  I tried, but didn't get it to run. It couldn't find the module factory.
Have you ever tried it?

**Comment by kclercR310** [comment]
I also tried to set AOT by default to `true`but then it won't compile at all.
It can't find the lazy module.

**Comment by qdouble** [comment]
@kclercR310 I got the current config from other projects that used ngtools, I don't think that it's necessary to set it up that way when using it

**Comment by kclercR310** [comment]
@qdouble ok.
I'm not very familiar with this building / compiling stuff. I just thought, that when you use platformBrowserDynamic stuff, the JIT compiler is packed in the bundle anyway, and that would increase the size of the bundle a lot.

**Comment by qdouble** [comment]
I just ran a test, currently: index.js.gz 184 kB. The commit before I started using ngtools: index.js.gz     184 kB. So there doesn't seem to be any difference or need to use platformBrowser when using ngtools.
