### ISSUE TITLE
ngrx/store-log-monitor has incorrect peer dependency "@angular/core@^2.0.0-rc.6".

### ISSUE THREAD

**Issue by webmobiles** [qdouble/angular-webpack2-starter#287]
I've got  a warning:

$yarn
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@ngrx/store-log-monitor@3.0.2" has incorrect peer dependency "@angular/core@^2.0.0-rc.6".
[4/4] 📃  Building fresh packages...
success Saved lockfile.

it's not really important? or someone forget to update to @angular/core 4?

**Comment by t-p-l-k** [comment]
@webmobiles switch to https://github.com/ngrx/store-devtools

**Comment by qdouble** [comment]
not sure if this still comes up, but it isn't really important
