### ISSUE TITLE
Are *.dll.js necessary in index.html ?

### ISSUE THREAD

**Issue by stefan-krajnik** [qdouble/angular-webpack2-starter#291]
What is the purpose of this block of code in `index.html` ?
```
<div id="str-dlls">
	<%= '<' %>script src="/polyfill.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
	<%= '<' %>script src="/vendor.dll.js"<%= '>' %><%= '<' %>/script<%= '>' %>
</div>
````

**Comment by Dragomir-Ivanov** [comment]
These files are loaded in development mode, but not in production. Have the same question.

**Comment by qdouble** [comment]
They are just there for dev mode... I could have scripted it with the Webpack plugin instead, but there are some issues when doing it with universal, so I opted for that approach.
