### ISSUE TITLE
why this starter don't use webpack-dev-server

### ISSUE THREAD

**Issue by webmobiles** [qdouble/angular-webpack2-starter#292]
or     "server:dev": "npm-run-all -p -r webdev sass:watch", is equivalent ?

**Comment by qdouble** [comment]
webdev is webpack-dev-server: https://github.com/qdouble/angular-webpack2-starter/blob/master/package.json#L13 . It's just set to run the sass:watch command in parallel to compile this file: src/app/styles.scss
