### ISSUE TITLE
Universal:aot inline css

### ISSUE THREAD

**Issue by dugin** [qdouble/angular-webpack2-starter#293]
Is there a way to move the generated inline css to his own style.css? I tried messing with extract-text-webpack-plugin but i wasn't able to generate it.

Thanks in advance

**Comment by qdouble** [comment]
You should be able to do it if you change up the webpack config, but I don't like that setup for my projects because you then have to start worrying about components styles being cached in the browser. I prefer just to put anything that doesn't change often in the main styles.scss file.

**Comment by dugin** [comment]
Hmm, i see. Do you know if this inline css impact SEO in any way? And if i wanted to add this on a separated file, would you know how to configure this on webpack?

**Comment by qdouble** [comment]
The extract-text-webpack-plugin should be able to do it... you probably can find an implementation by search github for projects with it. I don't think there should be any SEO impact but I'm not an SEO expert.
