### ISSUE TITLE
Looking for hints for the Apollo Client and the Universal Rendering set up

### ISSUE THREAD

**Issue by josoroma** [qdouble/angular-webpack2-starter#294]
Since last weekend I have been working on connecting and combining the Apollo Client with this amazing starter, now I can safely say that I have this GraphQL experiment working very sweet on the Default Side (yarn start) but I still don't get it working on the Universal side (yarn universal).

#### Code

 * https://github.com/josoroma/angular-webpack2-starter/tree/production/src/app/features/graph

#### Screenshot

![WIP](https://github.com/josoroma/angular-webpack2-starter/raw/production/src/assets/dist_root/material-ngrx-graphql.gif)

References: http://dev.apollodata.com/angular2/server-side-rendering.html

Thanks in advance!

**Comment by qdouble** [comment]
Hmm, not sure as I don't really have much experience apollo or graphql. Universal can be tricky when it comes to anything that interacts with the Dom. Would probably be a better question for the angular repo or stackoverflow.

**Comment by josoroma** [comment]
@qdouble 

 * http://dev.apollodata.com/angular2/server-side-rendering.html#server-initialization

```
No changes are required to client queries to support this, so your Apollo-based Angular UI should support SSR out of the box.
```
I made a typo, now `graph` route on the server and Universal side is working very nicely:

https://github.com/josoroma/angular-webpack2-starter/commit/d6fa7bf64bffc78e32d5811bd67fcccea88531b2

Refrence:
