### ISSUE TITLE
Yarn link Issues

### ISSUE THREAD

**Issue by matt328** [qdouble/angular-webpack2-starter#295]
I have a library I created using this generator: https://github.com/jvandemo/generator-angular2-library.  When using npm or yarn link to develop the library against my application I've created using this starter I get an error building the project.

- Create a new project with this starter, `my-project`
- Create a new library with the generator I linked to above, `my-library`
- In `my-library`, run `npm install`, `npm run build`, and `npm link`
- In `my-project`, run `yarn`, `yarn link my-library`
- Add `SampleModule.forRoot()` to the `APP_IMPORTS`
- `yarn start` produces the following error:

```Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.```

I have tried the library with 3 other starters, and no issues at all with npm or yarn link.  Unfortunately the other starters don't provide all of the features this one does, so I would like to stick with this one.  I'm not deeply familiar yet with all the nuances of webpack and typescript, and each starter seems to have its own strategy of abstracting away each config, so I'm having alot of trouble even comparing configs to figure out why this starter in particular does not like `npm link`.

If I run `npm pack` on `my-library`, then `yarn add <full path to .tgz file>` it works, but that is a really cumbersome development process considering you have to bump a version number to get yarn add to recognize that files have changed.  It is preferable to just rebuild the library and have the client application pick up the changes and rebuild and reload itself.

**Comment by qdouble** [comment]
closing for now, let me know if this is still an issue
