### ISSUE TITLE
[BUG] No NgModule metadata found for 'BrowserAppModule'

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [qdouble/angular-webpack2-starter#298]
Hi,

I'm having a problem on my application that when I try to build universal:aot, I get the following error message on browser console:

`No NgModule metadata found for 'BrowserAppModule'.`

and the application won't run properly.

**Comment by bhardwajvarun** [comment]
@JoaoPauloCMarra were you able to fix this? I'm also having a similar issue.

**Comment by nhutcorp** [comment]
@bhardwajvarun I have fixed this problem, check this https://github.com/nhutcorp/angular-webpack2-starter

**Comment by sbechet** [comment]
I  can confirm bug:

# master

```
$ git checkout master
$ npm install
$ npm run prodserver
```
Then : `No NgModule metadata found for 'BrowserAppModule'`

# no-universal-support

```
$ git checkout no-universal-support
$ sed -i 's|dist/client|dist|' prodserver.js webpack.config.ts
$ npm install
$ npm run prodserver
```
Then : `No NgModule metadata found for 'BrowserAppModule'`

# minimal branch

```
$ git checkout minimal
$ sed -i 's|dist/client|dist|' prodserver.js webpack.config.ts
$ npm install
$ npm run prodserver
```
Then : `No NgModule metadata found for 'BrowserAppModule'`

# Full Stack 

```
zone.js:195 Uncaught Error: No NgModule metadata found for 'BrowserAppModule'.
    at NgModuleResolver.resolve (compiler.es5.js:14063)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:14647)
    at JitCompiler._loadModules (compiler.es5.js:25814)
    at JitCompiler._compileModuleAndComponents (compiler.es5.js:25773)
    at JitCompiler.compileModuleAsync (compiler.es5.js:25735)
    at PlatformRef_._bootstrapModuleWithZone (core.es5.js:5016)
    at PlatformRef_.bootstrapModule (core.es5.js:5002)
    at HTMLDocument.main (main.browser.ts:25)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:191)
```

**Comment by sbechet** [comment]
I tried @nhutcorp patch without success:

```
diff --git a/package.json b/package.json
index 4fb5d86..3566c8b 100644
--- a/package.json
+++ b/package.json
@@ -75,7 +75,7 @@
     "zone.js": "~0.8.9"
   },
   "devDependencies": {
-    "@ngtools/webpack": "^1.3.1",
+    "@ngtools/webpack": "1.4.1",
     "@types/express": "~4.0.35",
     "@types/ip": "~0.0.29",
     "@types/jasmine": "2.5.43",
```

**Comment by nhutcorp** [comment]
@sbechet let's try this https://github.com/nhutcorp/angular-webpack2-starter/commit/d92ffaf03c844e9ecfa8dfc8528b50138a4cc81c
I have update @ngtools/webpack to latest and re-added some old files for fix the "No NgModule metadata found ..." problem.

**Comment by sbechet** [comment]
Hello nhutcorp, thank you very much, AOT is working perfectly now!
