### ISSUE TITLE
Is lazy module loading implemented?

### ISSUE THREAD

**Issue by ShankarSumanth** [qdouble/angular-webpack2-starter#299]
Hi @qdouble ,

I was just wondering if lazy module loading is really implemented? I thought the lazy feature module was lazy loaded. I realised this very recently after migrating my whole application that lazy loading was not really lazy loaded. It definitely creates the chunks but all the chunks were loaded during the initial app rendering. 

For example, 
In this starter, when I navigate to Lazy route/Lazy module there has to be a network traffic, request to fetch this particular module, but I couldn't find any in the developers console. 
After investigating I found that `0.index.js` which is the lazy loaded chunk was already loaded during the first call to the server.

**Comment by qdouble** [comment]
That's because it's set to preloadAllModules https://github.com/qdouble/angular-webpack2-starter/blob/master/src/app/app.module.ts#L45

You can remove that part if you want traditional lazy loading behavior, but preloading makes it more seamless to the user.

**Comment by ShankarSumanth** [comment]
That worked. Thanks :)
