### ISSUE TITLE
[QUESTION] Material2

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [qdouble/angular-webpack2-starter#300]
Any plans on workaround for material beta-7/beta-8?

**Comment by nhutcorp** [comment]
I have clone material design source and make it suite for universal, you can check it here check this https://github.com/nhutcorp/angular-webpack2-starter

**Comment by kodeine** [comment]
material 2 beta 11 is out and now requires Angular 4.4.3 or greater...

**Comment by nhutcorp** [comment]
@kodeine https://github.com/nhutcorp/angular-webpack2-starter has updated
