### ISSUE TITLE
Update ngrx to ver. 4

### ISSUE THREAD

**Issue by sutkovoy** [qdouble/angular-webpack2-starter#303]
@qdouble , hi! Thanks for your job. Can you, please, update starter to ngrx 4?

**Comment by losorio35** [comment]
+ 1

**Comment by d3viant0ne** [comment]
There are outstanding issues in 4.x that make upgrading to the new release version impractical if not impossible.

**Comment by sutkovoy** [comment]
@d3viant0ne, what the issues?

**Comment by qdouble** [comment]
Updated to ngrx 4
