### ISSUE TITLE
Webpack 3 upgrade

### ISSUE THREAD

**Issue by kadosh1000** [qdouble/angular-webpack2-starter#306]
Hi,
Are there any plans to upgrade the seed to use webpack 3 instead of webpack 2?

**Comment by HristoKolev** [comment]
what are the breaking changes?

**Comment by Justus-Maier** [comment]
I successfully updated to Webpack 3 and its Dev Server (2.8). It worked seemlessly. Only this warning pops up:
` 23% building modules 113/117 modules 4 active ...c\node_modules\rxjs\operator\share.js
(node:5040) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.`
I don't know which plugin is causing this, in any case it's not critical for now.

@qdouble please update package.json & yarn.lock with Webpack 3 and Angular 4.4

**Comment by losorio35** [comment]
+1

**Comment by nhutcorp** [comment]
Latest update Webpack 3, Angular 4.4 and Material Design is here:
https://github.com/nhutcorp/angular-webpack2-starter

**Comment by qdouble** [comment]
Updated
