### ISSUE TITLE
browser caching - Chunk hashes in file names

### ISSUE THREAD

**Issue by kadosh1000** [qdouble/angular-webpack2-starter#310]
Hi, are there any plans to add chunk hashes to build files any time soon?

If not, how would you recommend on doing so?

**Comment by d3viant0ne** [comment]
Been a while since I looked at this but from a webpack perspective the pattern below should get you at least part of the way. Please not you can't just copy & paste that.

rest of the docs related to `config.output` can be found here https://webpack.js.org/concepts/output/

```
  if (!DLL) {
    config.output = {
      path: resolveRoot('dist'),
      filename: !PROD ? '[name].bundle.js' : '[name].[chunkhash].bundle.js',
      sourceMapFilename: !PROD ? '[name].bundle.map' : '[name].[chunkhash].bundle.map',
      chunkFilename: !PROD ? '[id].chunk.js' : '[id].[chunkhash].chunk.js'
    };
  } else {
    config.output = {
      path: resolveRoot('dll'),
      filename: '[name].dll.js',
      library: '[name]'
    };
  }
```

**Comment by kadosh1000** [comment]
@d3viant0ne  Thanks, 
I hadve added the chunkhash with the `chunkhash-replace-webpack-plugin` and it indeed solved my problem :)
