### ISSUE TITLE
Angular 5 upgrade

### ISSUE THREAD

**Issue by kadosh1000** [qdouble/angular-webpack2-starter#311]
Wondered due to the release of Angular 5.0.0 if there is any plan to upgrade the project to Angular 5.0.0?

**Comment by losorio35** [comment]
+ 1

**Comment by fdambrosio** [comment]
+1

**Comment by pouyaz123** [comment]
+1

**Comment by qdouble** [comment]
updated. I'm going to start keeping this project up to date again.
